### ISSUE TITLE
Include a notification system to this project

### ISSUE THREAD

**Issue by httpdss** [archerysec/archerysec#103]
**Is your feature request related to a problem? Please describe.**
Would be nice to see a notification system on this project that would tell you about events happening. for example: "scan for project X has finished" or "new user has been created"

**Describe the solution you'd like**
The solution I propose is to use something like [pinax-notifications](https://github.com/pinax/pinax-notifications) or [django-notifications](https://github.com/django-notifications/django-notifications)

**Comment by anandtiwarics** [comment]
Yes, sure we'll work on this. Currently, I'm working on [multiple user access control](https://github.com/archerysec/archerysec/issues/104).

**Comment by httpdss** [comment]
@anandtiwarics excellent! 💯 👍

**Comment by bilelfeki** [comment]
Hello I have a project and I want to implement a notification system I would like to take a look to your work but I didn't find a branch or something else spetial for this issue . Could you help me thanks
