### ISSUE TITLE
Custom Tools and Plugins

### ISSUE THREAD

**Issue by rams3sh** [archerysec/archerysec#107]
It would be great if you could make a framework around addition of custom tools and custom parser for each tool to be added as a separate plugin within Archery something like ola jackhammer. Reference link given below :-

https://jch.olacabs.com/userguide/adding_new_tool/

This would help us to enhance the framework easily module by module.

**Comment by wheelq** [comment]
+ nmap
+ wapiti etc...

**Comment by anandtiwarics** [comment]
Duplicate of #16
