### ISSUE TITLE
Error while trying to launch burp suite pro scan 

### ISSUE THREAD

**Issue by awakenine** [archerysec/archerysec#108]
**Describe the bug**
While trying to run scan "Not Found: /webscanners/burp_launch_scan/"
Burp REST API set up with command:
`java -jar burp-rest-api-2.0.1.jar --headless.mode=false --burp.jar=/opt/BurpSuitePro/burpsuite_pro.jar`
Archerysec is installed with help of Automated installation.
**To Reproduce**
1. Go to archery web app Scan->Domain
2. Enter target URL
3. Select Burp Scanner
4. Launch

**Expected behavior**
Scan started

**Desktop (please complete the following information):**
 - OS: Kali linux

**Comment by itsgauravjain22** [comment]
On further investigation, I found that post request is giving 404 error on '/webscanners/burp_launch_scan/' endpoint. The following screenshot might be useful.

![1](https://user-images.githubusercontent.com/11793930/52841815-3e477e80-3123-11e9-9ecd-3f4fcea47032.png)

**Comment by anandtiwarics** [comment]
I've pushed the fix. Please confirm.
