### ISSUE TITLE
ArcherySec Docker Login

### ISSUE THREAD

**Issue by rmsferreira** [archerysec/archerysec#111]
After deploy archerysec in docker environment, the system is up and running but i don`t know what is the login credentials.

**Comment by anandtiwarics** [comment]
Please use the signup page to create account. However defaults credentials is admin/admin

**Comment by micxer** [comment]
Well, I did the same and cannot login using admin / admin. It just keeps putting me on the Sign in / Sign up page.

**Comment by anandtiwarics** [comment]
Please use the signup page. http://127.0.0.1:8000/signup/

**Comment by micxer** [comment]
Weird, at some point it did work with admin / admin. Nevermind.
