### ISSUE TITLE
Page not found (404)

### ISSUE THREAD

**Issue by evgeniysgs3** [archerysec/archerysec#112]
I try upload one ZAP report,and i click the button to download the report.Then it show ：

Request Method:	POST
Request URL:	http://92.53.91.89:8008/webscanners/get_scan_pdf/

Using the URLconf defined in archerysecurity.urls, Django tried these URL patterns, in this order:

^__debug__/
^admin/
^webscanners/ ^login/$ [name='login']
^webscanners/ ^signup/$ [name='signup']
^webscanners/ ^auth/$ [name='auth']
^webscanners/ ^logout/$ [name='logout']
^webscanners/ ^loggedin/$ [name='loggedin']
^webscanners/ ^$ [name='index']
^webscanners/ ^setting/ [name='setting']
^webscanners/ ^burp_setting [name='burp_setting']
^webscanners/ ^xml_upload [name='xml_upload']
^webscanners/ ^email_setting [name='email_setting']
^webscanners/ ^cookie_add [name='add_cookies']
^webscanners/ ^web_task_launch [name='web_task_launch']
^webscanners/ ^web_scan_schedule [name='web_scan_schedule']
^webscanners/ ^del_web_scan_schedule [name='del_web_scan_schedule']
^webscanners/ ^sel_login [name='sel']
^webscanners/ save_cookie [name='save_cookie']
^webscanners/ exclude_url [name='exclude_url']
^webscanners/ ^cookies_list
^webscanners/ ^cookies_del
^webscanners/ ^excluded_url_list
^zapscanner/
^acunetixscanner/
^burpscanner/
^arachniscanner/
^netsparkerscanner/
^webinspectscanner/
^projects/
^networkscanners/
^staticscanners/
^banditscanner/
^dependencycheck/
^findbugs/
^retirejsscanner/
^api/
^scanapi/
^login/$ [name='login']
^auth/$ [name='auth']
^logout/$ [name='logout']
^loggedin/$ [name='loggedin']
^signup/$ [name='signup']
^$ [name='zap_vuln_chart']
^dashboard/$ [name='dashboard']
^project_dashboard/$ [name='project_dashboard']
^web_dashboard/$ [name='web_dashboard']
^net_dashboard/$ [name='net_dashboard']
^proj_data/$ [name='proj_data']
^web_dash_data/$ [name='web_dash_data']
^net_dash_data/$ [name='net_dash_data']
^vuln_stat_dash/$ [name='vuln_stat_dash']
^api-token-auth/
^api-token-verify/
^api-token-refresh/
^osintscan/
^jira/
^tools/
^manual_scan/
^static\/(?P<path>.*)$
The current path, webscanners/get_scan_pdf/, didn't match any of these.

**Comment by green-george** [comment]
now have also tried installing on Kali VM
same result

**Comment by anandtiwarics** [comment]
we're still working on this functionality. We'll keep you update once it's fully working.

**Comment by anandtiwarics** [comment]
I'm closing this issue, as we have multiple format report download option available. I'll keep you updated once we have pdf generated report. thanks for reporting.
