### ISSUE TITLE
Support OWASP Dependency Check for vulnerability scanning

### ISSUE THREAD

**Issue by micxer** [archerysec/archerysec#116]
**Is your feature request related to a problem? Please describe.**
OWASP Dependency Check is one of the default tools when scanning for security issues in dependencies and has a well defined data format. This should be easy to integrate.

**Describe the solution you'd like**
Run dependency-check in my pipeline and upload the result to archery for analysis. Finally have some nice graphs and helpful information for our teams to act on.

**Comment by anandtiwarics** [comment]
We do have OWASP DependencyCheck and you can upload result in xml format. Also you can use our API or CLI to upload dependecyCheck results. 

```
$pip install archerysec-cli

$archerysec-cli -s http://archerysechost:port -u ${ARCHERY_USER} -p ${ARCHERY_PASS} --upload --file_type=XML --file=/home/archerysec/dependency-check-report.xml --TARGET=''yourprojectname'' --scanner=dependencycheck --project_id=''$PROJECT_ID

```

For more details you can visit our [developer site](https://developers.archerysec.info/?shell#) or [Archerysec-cli](https://github.com/archerysec/archerysec-cli)

**Comment by micxer** [comment]
Ah, didn't find that in the docs. Thanks für updating them.

**Comment by rafaelsilvaa10** [comment]
Hello, do you have an example of the call on api?

**Comment by anandtiwarics** [comment]
hi @rafaelsilvaa10 

you can check our [API Documentation](https://developers.archerysec.com/) also you can use [ArcherySec-cli](https://github.com/archerysec/archerysec-cli). 

here our blog on [how you can integrate with your ci/cd pipeline jenkins](https://blog.archerysec.com/Integrate-ArcherySec-OWASP-ZAP-in-Jenkins-CICD-Pipeline/)

Also, we follow devsecops philosophy by integrating and managing vulnerability using Archerysec [Github Action](https://github.com/archerysec/archerysec/blob/workflow/.github/workflows/integration-test.yml)  

Still, lots of development going on, and might be some info are not updated. feel free to raise an issue and ask questions.

**Comment by rafaelsilvaa10** [comment]
Hello @anandtiwarics 

I am using archerySec on my cicd. At this point, you need to upload an XML (dependency check).

Through the CLI I can, however need to do it via REST API. in a problem I saw you commenting that it is possible, however in the documentation I found nothing.

`curl --location --request POST 'http://myserver.com/webscanners/xml_upload' --header 'Content-Type: application/json' --header 'Authorization: JWT MYTOKENN ' --data-raw '{"target":"testingg", "scanner":"dependencycheck", "project_id":"1c203531-6064-48f7-b8b5-8b81e2fa5562"}'`


do you have any example of REST calls to upload?

**Comment by rafaelsilvaa10** [comment]
I didn't want to install the cli on my build server.

**Comment by anandtiwarics** [comment]
please look into our [postman collection](https://github.com/archerysec/archerysec/blob/master/Postman%20Collection/Archery_REST_API.postman_collection_V2)

**Comment by anandtiwarics** [comment]
report upload [REST API](https://github.com/archerysec/archerysec/blob/1cb436e8e081ffb5d4a710db720807ccd826088a/Postman%20Collection/Archery_REST_API.postman_collection_V2#L500)
