### ISSUE TITLE
Unable to see web scans after pull

### ISSUE THREAD

**Issue by outdoorguy007** [archerysec/archerysec#118]
I pulled the latest version down, but now I don't seem to be able to see the previous web scans.  Its keeps giving me this error.

no such column: webscanners_zap_scan_results_db.scanner

Is there an update that I am supposed to run?  I just did the normal install again

**Comment by anandtiwarics** [comment]
@outdoorguy007 look like database has not been migrated properly and scanner column has not been created. Fixed this issue, please pull now and run install.sh script.
additionally, run the below command in project root folder,
 `python manage.py migrate ` 

Let me know if you still getting error.

**Comment by evgeniysgs3** [comment]
After update migrations I get the error:
python manage.py migrate
![image](https://user-images.githubusercontent.com/12111054/52403196-c8407900-2a8b-11e9-910e-104ebbc6409f.png)

**Comment by anandtiwarics** [comment]
Reset the migrations for the "built-in" apps by running below commands:

`python manage.py migrate --fake`

`python manage.py makemigrations`

`python manage.py migrate --fake-initial`

**Comment by evgeniysgs3** [comment]
![image](https://user-images.githubusercontent.com/12111054/52412265-db5f4300-2aa3-11e9-838e-1e86de7d4aa1.png)

Is that right?

**Comment by outdoorguy007** [comment]
Yes I do still get the error after running the install and migrate.

Tim

**Comment by evgeniysgs3** [comment]
My ZAP scan results in production version:
![image](https://user-images.githubusercontent.com/12111054/52416487-4f531880-2aaf-11e9-8097-8527a6a8bade.png)

**Comment by anandtiwarics** [comment]
@evgeniysgs3 have you properly integrated zap ? 

 https://docs.archerysec.info/Scanners/zap-scanner/

**Comment by evgeniysgs3** [comment]
Yes of course I configured ZAP on my local interface with Internet access and configured Archery:
![image](https://user-images.githubusercontent.com/12111054/52419495-d4d9c700-2ab5-11e9-8916-2118fd4ec520.png)

**Comment by evgeniysgs3** [comment]
When I try to start OWASP ZAP scanning. I get this messages on my host with zap.sh installed and running:
![image](https://user-images.githubusercontent.com/12111054/52532326-a132b300-2ce8-11e9-92a9-52b5f7bda044.png)
