### ISSUE TITLE
Wrong link in openzap breadcrumb menu of "Vulnerability Details" in Vulnerabilty Page

### ISSUE THREAD

**Issue by itsgauravjain22** [archerysec/archerysec#120]
**Describe the bug**
After viewing the found path traversal vulnerability of openzap and clicking **Vulnerability Details**, I got 404 not found error. I found the url was 
`/zapscanner/zap_vuln_list/?scan_id=547f917a-07fb-4c27-802d-bdf788fb1e11`
instead of
`/zapscanner/zap_list_vuln/?scan_id=547f917a-07fb-4c27-802d-bdf788fb1e11`

**To Reproduce**
1. Go to 'Vulnerability' page.
2. Click on 'Vulnerability Details' on breadcrumb menu.
3. See 404 not found error.

**Expected behavior**
We should navigate to 'Vulnerabilities List' page.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: chrome

**Comment by anandtiwarics** [comment]
@itsgauravjain22 thanks for reporting an issue. We are looking into this.

**Comment by anandtiwarics** [comment]
Not able to reproduce. Closing the issue.
