### ISSUE TITLE
Page not found (404) error in Edit link in vulnerability page.

### ISSUE THREAD

**Issue by itsgauravjain22** [archerysec/archerysec#121]
**Describe the bug**
I have got the 404 error while clicking `Edit` link in found vulnerability.

**To Reproduce**
1. Go to 1. 'Vulnerability' page after zap scan results.
2. Click on 'Edit' link of top right corner of page.
3. See 404 error.

**Expected behavior**
The application should navigate to 'edit vulnerability' page.

**Screenshots**
![1](https://user-images.githubusercontent.com/11793930/52549168-d679f680-2df7-11e9-8135-702e97657adf.png)
![2](https://user-images.githubusercontent.com/11793930/52549170-daa61400-2df7-11e9-8b47-9030e551d0f0.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19
 - Browser: chrome v72.0.3626.96 (Official Build) (64-bit)

**Additional context**
The blue edit button also points to '#' instead of 'edit vulnerability' page, which should be fixed.

**Comment by anandtiwarics** [comment]
Hi @itsgauravjain22 thanks for reporting an issue. We are looking into this.
