### ISSUE TITLE
Extensibility of ArcherySec through custom plugins

### ISSUE THREAD

**Issue by itsgauravjain22** [archerysec/archerysec#122]
A great software comes with extensibility through plugins for eg, wordpress. Through plugins, we can add, update or remove the fundionality, we desire. Also, custom developement of plugins becomes easy and modular if proper developement documentation is available.
I would like to have all scanners and parser registered as plugins to core system. The core sytem act as a dashboard and plugins for scanners and parsers extend the functionaliy of core sytem.
I highly reccommend this for present ArcherySec, as there exist many scanning tools but there's limited set of supported tools to import for reports.

**Comment by anandtiwarics** [comment]
Hi @itsgauravjain22 

We're working to integrate multiple scanners plugins & parser. #18

**Comment by itsgauravjain22** [comment]
It's great that archerysec is supporting many popular tools built-in. All I am suggesting that these are not all the available tools. And some organization is using some set of tools and others are different set of tools.
Now, the problem to this can be resolved by having a scalable system where we have the ability to remove and add the functionality using plugins. It would be also easier to build the custom plugin for the desired web scanner without touching a single line of code in core application.
It would attract other developers to build the plugin for core archerysec to enhance the functionality and overall increases the modularity.

**Comment by anandtiwarics** [comment]
Hi @itsgauravjain22 thanks for your feedback. Archerysec uses the scanners API and we'll write plugins if scanners are having API endpoint. You would see multiple scanners plugin in our upcoming releases where organization have the flexibility to add and remove scanners from archerysec.

**Comment by itsgauravjain22** [comment]
@anandtiwarics  Its great to hear that you liked the idea.
