### ISSUE TITLE
Mysql database support and documentation

### ISSUE THREAD

**Issue by itsgauravjain22** [archerysec/archerysec#123]
**Is your feature request related to a problem? Please describe.**
Most of the server have opt for mysql server for various application. But mysql is currently not supported and documentation doesn't provide any help. Though a person could take help from docker-compose file, but it's also using postgre-sql. So there's no help for using mysql server with archery sec.

**Describe the solution you'd like**
It would be great if documentation of archerysec can show integration with mysql server. For my purpose, I managed to run archerysec with mysql server by following steps:

- Execute `sudo apt-get install python-dev default-libmysqlclient-dev` in ubuntu system. For different systems, refer to [this](https://pypi.org/project/mysqlclient/).

- Adding `mysqlclient==1.4.2` in "requirements.txt" file.

- Modify  `'ENGINE': 'django.db.backends.mysql'` in "archerysecurity/settings.production.py" file and filling proper mysql database in same file.

- Modify `os.environ.setdefault("DJANGO_SETTINGS_MODULE", "archerysecurity.settings.production")` in "manage.py" file.

- Follow the install steps provided in [https://docs.archerysec.info/getting-started/Installation/](url).

The application runs normal on following the above steps. But I encounter a bug, when uploading accunetix xml report. Kindly help me regarding the following issue:

```
OperationalError at /webscanners/xml_upload/
(1366, "Incorrect string value: '\\xC2\\x80\\xC2\\x93ha...' for column 'VulnDetails' at row 1")
Request Method:	POST
Request URL:	http://localhost:9000/webscanners/xml_upload/
Django Version:	1.11.20
Exception Type:	OperationalError
Exception Value:	
(1366, "Incorrect string value: '\\xC2\\x80\\xC2\\x93ha...' for column 'VulnDetails' at row 1")
Exception Location:	/root/archerysec/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py in query, line 224
Python Executable:	/root/archerysec/venv/bin/python
Python Version:	2.7.15
Python Path:	
['/root/archerysec',
 '/root/archerysec/venv/lib/python2.7',
 '/root/archerysec/venv/lib/python2.7/plat-x86_64-linux-gnu',
 '/root/archerysec/venv/lib/python2.7/lib-tk',
 '/root/archerysec/venv/lib/python2.7/lib-old',
 '/root/archerysec/venv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/root/archerysec/venv/local/lib/python2.7/site-packages',
 '/root/archerysec/venv/lib/python2.7/site-packages',
 '/root/archerysec/venv/local/lib/python2.7/site-packages/odf',
 '/root/archerysec/venv/local/lib/python2.7/site-packages/odf',
 '/root/archerysec/venv/local/lib/python2.7/site-packages/odf',
 '/root/archerysec/venv/local/lib/python2.7/site-packages/odf',
 '/root/archerysec/venv/local/lib/python2.7/site-packages/odf',
 '/root/archerysec/venv/local/lib/python2.7/site-packages/odf',
 '/root/archerysec/venv/local/lib/python2.7/site-packages/odf']
Server time:	Wed, 13 Feb 2019 10:20:18 +0000
```

**Comment by anandtiwarics** [comment]
Hi, @itsgauravjain22 thanks for reporting an issue. We are looking into this.
