### ISSUE TITLE
Incomplete "Plugin Output" field data in nessus upload scans

### ISSUE THREAD

**Issue by itsgauravjain22** [archerysec/archerysec#124]
**Describe the bug**
I get incomplete data value of "Plugin Output : " field after uploading nessus scans results.

**To Reproduce**
1. Upload nessus scan report on archery sec.
2. Click on any vulnerability which has more than one <plugin_output> tags.
3. Observe the incomplete output in archery sec.

**Expected behavior**
We should get the complete multiple <plugin output> tags output separated by a single line.

**Screenshots**
Following is the screenshot of archerysec output:
![screenshot-80 240 31 168-9000-2019 02 13-19-11-17](https://user-images.githubusercontent.com/11793930/52715782-5607f100-2fc3-11e9-9cd1-760b4aa2f96b.png)

Following is the screenshot of html report of nessus scan:
![screenshot from 2019-02-13 19-22-28](https://user-images.githubusercontent.com/11793930/52716544-fa3e6780-2fc4-11e9-83ed-bcf9a7e5996f.png)

**Desktop (please complete the following information):**
 - OS: linux mint
 - Browser: chrome
 - Version: 72.0.3626.96 (Official Build) (64-bit)

**Additional context**
The issue seems to in parser which is incorporating only last <plugin output> tag result and also delimited by ':' character.

**Comment by itsgauravjain22** [comment]
After further investigating the issue, it was seen that archery sec parser separates the 'location' tag and separates the same vunerability with different port and increase the count. This is functionally correct but I couldn't find the discrete vulnerability counts, instead I get the report of separate instances of each found vulnerable ports. 
In my case, I have 24 discrete vulnerabilities in nessus report, but after uploading nessus report to archery sec, I got the count of 44 in total field. Now from this '44' count, anyone can be misleaded as 44 discrete vulnerabilities are found. 
This behaviour is same for Openvas report and should be improved.

**Comment by anandtiwarics** [comment]
Hi @itsgauravjain22 thanks for reporting an issue. We are looking into this.
