### ISSUE TITLE
 Incorrect zap scan completion when the underlying zap scanner service is not running 

### ISSUE THREAD

**Issue by itsgauravjain22** [archerysec/archerysec#125]
**Describe the bug**
Consider the underlying zap scanner service is crashed, and we try to launch the zap scanner through archerysec. The output of the scenario is that 'scan launched' message is printed on 'scan launch' page and scan first display '0' on 'zap scan list' page. The situation goes futher wrong on subsequent page reload of 'zap scan list' page, when the started zap scan displays 100% with none vulnerabity found.

**To Reproduce**
1. Stop the underlying zap process on the sytem.
2. Go to 'Scan Launch' page and start the zap scan.
3. Observe the 'scan launched' message.
4. Navigate to 'ZAP Scans Result' page and obseve the launched scan with '0' on progress bar.
5. Reload the 'ZAP Scans Result' page.
6. Observe the launched scan with 100% in progess bar.

**Expected behavior**
The progress bar should be displayed with error message, for eg. 'zap scan could not be launched'. or the scan should not be visible on zap scan page overall and error message on 3rd step should be printed. 

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Chrome

**Comment by anandtiwarics** [comment]
Hi @itsgauravjain22 thanks for reporting an issue. We are looking into this.

**Comment by anandtiwarics** [comment]
fixed
