### ISSUE TITLE
Incorrect total vulnerability count in arachni web scanner result

### ISSUE THREAD

**Issue by itsgauravjain22** [archerysec/archerysec#126]
**Describe the bug**
I tried arachni web scanner with archerysec with successful integration. But I found the incorrect **total vulnerability** scan count in report.

**To Reproduce**
1. Go to 'scan launch' page and start arachni web scanner.
2. Navigate to 'Arachni Scans Result' page.
3. Observe the 'Total Vulnerability' count.

**Expected behavior**
The 'Total Vulnerability' is '0', even a single vulnerabilty is found.

**Screenshots**
![screenshot-80 240 31 168-9000-2019 02 14-15-58-55](https://user-images.githubusercontent.com/11793930/52781775-6d9eb280-3073-11e9-85be-538a4e5fa950.png)
Duplicate issue counter is '1' because the scan has been launched after a first scan.

![screenshot-80 240 31 168-9000-2019 02 14-15-59-52](https://user-images.githubusercontent.com/11793930/52781784-742d2a00-3073-11e9-9116-f6b03cb3d5b6.png)

![screenshot-80 240 31 168-9000-2019 02 14-16-00-20](https://user-images.githubusercontent.com/11793930/52781789-78f1de00-3073-11e9-9779-145f4cc7bf68.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser Chrome

**Comment by anandtiwarics** [comment]
Hi @itsgauravjain22 thanks for reporting an issue. We are looking into this.

**Comment by anandtiwarics** [comment]
Duplicate of #127
