### ISSUE TITLE
Incorrect vulnerability counts on uploading accunetix reports

### ISSUE THREAD

**Issue by itsgauravjain22** [archerysec/archerysec#127]
**Describe the bug**
The accunetix reports section is reporting completely incorrect vulnerability counts. And morever, it got completely messed up if I try to upload the same accunetix report again with 'Total Vulnerability' count set to '0'.

**To Reproduce**
1. Upload the 'accunetix' xml report.
2. Navigate to 'Acunetix Scans Result' page.
3. Observe the incorrect vulnerability counts.
4. Again upload the 'accunetix' xml report.
5. Navigate to 'Acunetix Scans Result' page.
6. Again observe the incorrect vulnerability counts behaviour.

**Expected behavior**
The vulnerability count functionality should work correctly. 

**Screenshots**
Archerysec Acunetix Scans Result:
![screenshot-80 240 31 168-9000-2019 02 14-16-44-03](https://user-images.githubusercontent.com/11793930/52783948-89a55280-3079-11e9-9f59-e086e5213bca.png)

Actual Accunetix PDF Report of the same scan:
 
![screenshot from 2019-02-14 17-00-18](https://user-images.githubusercontent.com/11793930/52784115-0d5f3f00-307a-11e9-9b16-9ebd0ca7006c.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Chrome

Additional Comments refering from screenshots:
On further investigation, '35' count is incorrect. Instead '22' is the correct discrete vunerabilities in accunetix report, which is correctly displayed in duplicates field of subsequent scan result.

**Comment by anandtiwarics** [comment]
Hi @itsgauravjain22 thanks for reporting an issue. We are looking into this.

**Comment by anandtiwarics** [comment]
Fixed the issue. Please pull and migrate the code.

`python manage.py migrate`
