### ISSUE TITLE
Incorrect url in 'Vulnerability List' of Accunetix Report

### ISSUE THREAD

**Issue by itsgauravjain22** [archerysec/archerysec#128]
**Describe the bug**
For 'Acunetix Scans Result', the url field of vulnerability is set to incorrect value of url and the url value is same for all found vulnerabilities.

**To Reproduce**
1. Upload the 'accunetix' scan report.
2. Navigate to 'Acunetix Scans Result' page.
3. Click on scanned domain and then to any found vunerabilty.
4. Observe the incorrect 'URL' field value.

**Expected behavior**
The 'URL' should be correct with each found vulnerability. For multiple url's having the same vulnerability, there should be different columns for each url. 

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser Chrome

**Comment by anandtiwarics** [comment]
Hi @itsgauravjain22 thanks for reporting an issue. We are looking into this.

**Comment by itsgauravjain22** [comment]
On further investigating the issue, it is observed that 'False Positive Vulnerability List' functionality is completely broken due to above bug.

**Comment by anandtiwarics** [comment]
need Accunetix pro version report sample.

**Comment by itsgauravjain22** [comment]
Sample report of accunetix pro is below:
[test_accunetix.zip](https://github.com/archerysec/archerysec/files/2908723/test_accunetix.zip)
