### ISSUE TITLE
Negative number displayed in arachni web scan progress bar

### ISSUE THREAD

**Issue by itsgauravjain22** [archerysec/archerysec#129]
**Describe the bug**
Many times, I found negative number on progress bar of arachni web scan after launching it. It could be an indicator that logic behind the progress bar is not working correctly and report the incorrect scan progress on web scans. 

**To Reproduce**
1. Launch Arachni web scan.
2. Navigate to 'Arachni Scans Result' page.
3. Observe the launched arachni web scan progress.

**Expected behavior**
The progress bar shoud display correct arachni web scan progress.

**Screenshots**
![3](https://user-images.githubusercontent.com/11793930/52836707-b86f0780-3111-11e9-8fb9-33c15c4aa7e6.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser ; Chrome

**Comment by anandtiwarics** [comment]
Hi, @itsgauravjain22 its feeding from Arachni scanner and calculating according. We are aware of this issue.

**Comment by itsgauravjain22** [comment]
Hello @anandtiwarics, thanks for the confirmation.
