### ISSUE TITLE
Add Nexpose in Scanners parser & Plugin

### ISSUE THREAD

**Issue by NRGLine4Sec** [archerysec/archerysec#138]
Can you add Nexpose in Scanners parser & Plugin ?

**Comment by mich4e1** [comment]
The same question is interested, how to add integration with Nexpose and/or Qualys (or import XML)?

**Comment by anandtiwarics** [comment]
Could you please send us a report sample in XML format for both Qualys and Nexpose?

**Comment by mich4e1** [comment]
> Could you please send us a report sample in XML format for both Qualys and Nexpose?

At the moment work on it. Once I have the report with share here.

**Comment by zorianix** [comment]
Hi Anand I would like to contribute to the project by adding plugin support like qualys , nexpose , can you let me know how can i contribute

**Comment by anandtiwarics** [comment]
Duplicate of #16
