### ISSUE TITLE
NameError at /networkscanners/OpenVAS_xml_upload/

### ISSUE THREAD

**Issue by wheelq** [archerysec/archerysec#144]
**Describe the bug**
NameError at /networkscanners/OpenVAS_xml_upload/

**To Reproduce**
1. Export OpenVAS report into XML file
2. Import file from step 1 into archerysec via Network Scans->OpenVAS
3. See error

**Screenshots**
OpenVAS has reported some issues:
![image](https://user-images.githubusercontent.com/1497172/55551322-6f2f4300-56d2-11e9-9027-ff39c0996baa.png)
So I have exported report into XML file, and while importing this file into archerysec I get the following response:
After importing the XML, archerysec did not parse any issues:
![image](https://user-images.githubusercontent.com/1497172/55551513-e5cc4080-56d2-11e9-9aca-199939d1bbcf.png)

**Comment by mich4e1** [comment]
you can see into my opened ticked [https://github.com/archerysec/archerysec/issues/304](url), maybe it will be useful for you.
And also be sure that you export proper XML from OpenVas (you should choose XML type from the list).

**Comment by wheelq** [comment]
why might it be useful? it is an issue
