### ISSUE TITLE
archerysec-cli fails to install

### ISSUE THREAD

**Issue by wheelq** [archerysec/archerysec#148]
What is needed exactly in order to install archerysec-cli?

![image](https://user-images.githubusercontent.com/1497172/55805378-375f3b80-5ad6-11e9-9da3-2dd5c5f16931.png)

**Comment by anandtiwarics** [comment]
`pip install archerysec-cli`

or 

```
$ git clone https://github.com/archerysec/archerysec-cli.git
$ cd archerysec-cli
$ pip install -r requirements.txt
```
for more details : [https://github.com/archerysec/archerysec-cli](https://github.com/archerysec/archerysec-cli)

**Comment by wheelq** [comment]
I have tried both options, please find screenshots below for both:

1. 
![image](https://user-images.githubusercontent.com/1497172/55806782-dd13aa00-5ad8-11e9-95ad-d7e7c4f2b2e9.png)

2. 
![image](https://user-images.githubusercontent.com/1497172/55806866-09c7c180-5ad9-11e9-9d07-70572f93d193.png)
