### ISSUE TITLE
Dashboard for projects fails with ProgrammingError at /proj_data/

### ISSUE THREAD

**Issue by wheelq** [archerysec/archerysec#149]
**Issue**
When trying to display project dashboard, app fails with an error (screenshot attached below)

**To Reproduce**
1. Navigate to Home->Dashboard
2. Click on a project
3. Error should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/1497172/55879850-71dcdd00-5b97-11e9-976c-f4aaaba9650a.png)

**Desktop (please complete the following information):**
 - OS: RHEL7.5
 - Browser chrome
 - Version: all latest (chrome+docker+image+docker-compose)

**Comment by anandtiwarics** [comment]
fixed this issue on #136 issue. 

could you please run `python manage.py migrate` and let me know.

**Comment by wheelq** [comment]
![image](https://user-images.githubusercontent.com/1497172/55882966-4fe65900-5b9d-11e9-8f1b-5ecdea4fb34f.png)

**Comment by anandtiwarics** [comment]
can you match `compliance/models.py` file with below fix ?

https://github.com/archerysec/archerysec/commit/24d976a8ebb855511eab2f07ad146738b2611f11#diff-0264a5d7303c9e752585351aa62f8b5b

**Comment by wheelq** [comment]
now it works. thank you
