### ISSUE TITLE
Make easier installation.

### ISSUE THREAD

**Issue by anandtiwarics** [archerysec/archerysec#19]

**Comment by astone75** [comment]
Hi,
It'd be a great idea to bundle all the "basic tools" inside your docker image, this way one could have everything wotking (openvas/burp/zap/arachni/nikto, etc.) out of the box making this really usable without spending a long time setting everything up.

**Comment by anandtiwarics** [comment]
Hi 

Thanks for your feedback @astone75  . We are already building Docker file containing basic tools.

Please have a look. https://github.com/archerysec/archerysec/blob/master/Dockerfile
