### ISSUE TITLE
Fix security issues in docker image

### ISSUE THREAD

**Issue by pieterlange** [archerysec/archerysec#20]
**Describe the bug**
The defaults for the docker image are quite insecure. This is a combined issue ticket for tracking specific issues such as:

  * Running the application as root
  * Building `FROM` an unversioned base image (which is also fairly large, embedding a ton of stuff you don't need)

This results in a **massive** image containing a ton of stuff we probably don't need. This influences container rescheduling (pull wait time) but also just more dead code that'll just contain vulnerabilities.

```
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
archerysec/archerysec   latest              529cb12f73f6        4 hours ago         2.71GB
```

To me its clear this (awesome) tool needs some packaging love.

**Expected behavior**
Package and run with secure defaults.

**Additional context**
This is a tracking issue for a PR i'm going to file separately.

Because a number of people here are still experimenting with all these tools and benefit from the kali base image i'm proposing to build 2 versions: one built using the currently existing build flow (basically embedding all of kali linux) and another `slim` image as is customary in the docker ecosystem with EG an alpine linux base image, containing the bare minimum toolchain to run the project.

Alpine linux, being a stripped down distribution, carries a number of security features such as not shipping much code by default, replacing glibc for musl and replacing openssl for libressl.

**Comment by anandtiwarics** [comment]
Thanks for your valuable inputs @pieterlange. We are still trying to figure out the best way to dockerize Archery. This is an experiment and a not secure way to implement. 

We'll look into this together and figure out the best way of implementation.

**Comment by pieterlange** [comment]
I'll try to come up with some decent PR some time soon, thanks for the cool project!

What do you think about maintaining 2 different container builds: one containing all of kali linux + archery and one based of alpine stripped bare to this apps' requirements (not containing ZAP etc)? We can kick off requests to other containers for the scans. This automatically helps for isolation and maintainability.

**Comment by anandtiwarics** [comment]
Sounds like a plan @pieterlange let's do it. 

Thanks.

**Comment by anandtiwarics** [comment]
Hi @pieterlange I have updated Dockerfile. Please have a look.
