### ISSUE TITLE
Edit project takes to 404

### ISSUE THREAD

**Issue by pl4g4** [archerysec/archerysec#21]
**Describe the bug**
After creating a project, I went to the project view. There is a button on the right side to edit the project. If you click on it it takes you to a 404 page.

http://127.0.0.1:8000/edit_vuln_dat/?vuln_id=

https://github.com/archerysec/archerysec/blob/dd4eae689dbc5eb1a260e0e2d12dc0272a45c6e2/projects/templates/project_view.html#L18

**Additional context**
I'm using the docker image.

**Comment by anandtiwarics** [comment]
Seems that the functionality was missing. Just pushed the code please check now.
