### ISSUE TITLE
Unable to sign in with the user created through the sign up page.

### ISSUE THREAD

**Issue by prasb** [archerysec/archerysec#28]
Dear Author,

Thank you for building an amazing product. Highly appreciate your efforts in bringing up this product. Can you please help me login to the system. Pulled a docker image as mentioned in the documentation. Started the docker and got the beautiful UI. May I know what is the default superuser created for docker image. I can't find anywhere mentioned in document. Also I used the signup page and trying to login with the user created. But  I am getting the below error.

Page 404.  
127.0.0.1:8000/catalog

Can you please help me here. Do i need to install the below requirement separately. If yes, what version f selenium and firefox needs to be used for working product.

Python 2.7
OpenVas 8
OWASP ZAP 2.7.0
Selenium Python Firefox Web driver

Thanks again for the great product. Looking forward for your help in setting up these.

Regards,
Prasanna B

**Comment by anandtiwarics** [comment]
Hi @prasb 

I have verified the docker and it's working fine for me. You can create a user using http://127.0.0.1:8000/signup/ signup link. 

Thanks,
Anand Tiwari
