### ISSUE TITLE
APIScan

### ISSUE THREAD

**Issue by raisabin** [archerysec/archerysec#291]
We are trying to install install archerysec in kali linux 2019.
When we clone Archery tool from github
There is APISan missing. 

**To Reproduce**
1. git clone https://github.com/archerysec/archerysec.git
2. cd /archerysec
3. pip install -r requirements.txt
4. python manage.py collectstatic
5. python manage.py makemigrations APIScan

**Desktop (please complete the following information):**
 - OS: Kali
 - DISTRIB_RELEASE=kali-rolling

**Comment by anandtiwarics** [comment]
this has been removed.
