### ISSUE TITLE
click "API" menu went wrong

### ISSUE THREAD

**Issue by alexanderhawl** [archerysec/archerysec#299]
**Describe the bug**
when I click API button in  profile, the page went wrong.
the information is:

Request Method: | GET
-- | --
http://192.168.8.129:8000/api/docs/
1.11.20
NoReverseMatch
u'api-docs' is not a registered namespace
/home/archerysec/.local/lib/python2.7/site-packages/django/urls/base.py in reverse, line 87
/usr/bin/python
2.7.15
['/home/archerysec/app',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/home/archerysec/.local/lib/python2.7/site-packages',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf']

**To Reproduce**
1.click profile menu
2.click the API

**Expected behavior**
page crash

**Screenshots**
<img width="1319" alt="屏幕快照 2019-05-28 下午2 05 14" src="https://user-images.githubusercontent.com/22365038/58454707-dd800700-8151-11e9-9fa0-6a846ae72e94.png">

**Desktop (please complete the following information):**
 - OS: Mac os
 - Browser safari

**Smartphone (please complete the following information):**

**Additional context**

**Comment by anandtiwarics** [comment]
https://developers.archerysec.com/ please use this.
