### ISSUE TITLE
Arachni Url empty

### ISSUE THREAD

**Issue by Grounz** [archerysec/archerysec#302]
**Describe the bug**
After an arachni webscan, the URL field is empty. Then during execution of arachni webscan the field is really completed with the url scanned.

**To Reproduce**
1. Call the webscan api with option ```scanner = arachni```
2. Run the scan
3. During execution, go to Dynamic Scan / Arachni, you must see the url field with your url scanned
4. After the scan execution, to Dynamic Scan / Arachni, you must see the fiel url which is empty

**Expected behavior**
Normally, we must see an url field not empty with the url scanned and passed in parameter

**Screenshots**
During execution:

![arachni_during_scan](https://user-images.githubusercontent.com/17216905/60447487-d1d9a180-9c23-11e9-9126-32c0256cd446.png)

After the scan:
![arachni_url_empty](https://user-images.githubusercontent.com/17216905/60447262-5aa40d80-9c23-11e9-8559-5f46956cb51b.png)

**Desktop (please complete the following information):**
 - OS:  Centos 7.5
 - Browser: chrome,
 - Version: 75.0.3770.100

**Additionnal**
Install mode: With docker and docker-compose

**Comment by zhangshuaiqiang-deepexi** [comment]
i meet this problem, too

**Comment by anandtiwarics** [comment]
@zhangshuaiqiang-deepexi @Grounz fixed the issue please check now.
