### ISSUE TITLE
Different UI view and functionality

### ISSUE THREAD

**Issue by mich4e1** [archerysec/archerysec#303]
**Describe the bug**
In the application present two different UI with different menu and functionality:

**To Reproduce**
1. Go to 'http://localhost:8000/dashboard/' 
![Screen Shot 2019-07-04 at 8 10 30 AM](https://user-images.githubusercontent.com/50629340/60642271-f60dcc00-9e37-11e9-9c8c-9ac7e7c6b8e3.png)

2. But on 'http://localhost:8000/tools/sslscan/' different interface:
![Screen Shot 2019-07-04 at 8 45 53 AM](https://user-images.githubusercontent.com/50629340/60642369-45ec9300-9e38-11e9-8f12-0bcacc9cabac.png)

**Expected behavior**
All menu fields should be present on the main UI.

**Desktop (please complete the following information):**
 - OS: [ Linux ]
 - Browser [Chrome  75.0.37, Firefox 67.0.4]

**Additional context**
Also, in the main project Dashboard page, on Scanners List table is not present mentioned tools: SSLScan, Nmap, Nmap Vulners, Nikto etc.
![Screen Shot 2019-07-04 at 8 56 03 AM](https://user-images.githubusercontent.com/50629340/60642838-daa3c080-9e39-11e9-85ca-73734f6a8422.png)

**Comment by prashasth** [comment]
Were you able to run nmap, nikto scan ?

Regarding UI, I am facing the same issue.

**Comment by anandtiwarics** [comment]
you would see all these functionalities in our upcoming 2.0 version. stay tuned.

**Comment by mich4e1** [comment]
> you would see all these functionalities in our upcoming 2.0 version. stay tuned.

Thanks.

**Comment by elenasarim** [comment]
> you would see all these functionalities in our upcoming 2.0 version. stay tuned.

Thank you. The tool is amazing.

**Comment by prashasth** [comment]
Any expected date for release? Amazing tool. Looking forward to the new version.

**Comment by anandtiwarics** [comment]
Hi @prashasth 

We have pushed the code #314 and added nmap, sslscan & nikto.

**Comment by prashasth** [comment]
@anandtiwarics  Thanks a lot. Will test it out and let you guys know the feedback. Incredible work guys. Really helpful. If there is anything I can help, please feel free to let me know.
