### ISSUE TITLE
Clair report not updating.

### ISSUE THREAD

**Issue by saravananicflix** [archerysec/archerysec#311]
**Describe the bug**
when I upload the Clair report it is not updating the table to show the number of high or Low.

**To Reproduce**
1. Go to static_scans
2. Click on 'clair'
3. click on upload XML
4. upload the attached json 
[gl-container-scanning-report.txt](https://github.com/archerysec/archerysec/files/3524050/gl-container-scanning-report.txt)

5. you will see 100% completed but the table will still show 0 for all the severity 

**Expected behavior**
The table should be updated according to the JSON file.

**Screenshots**
![Screen Shot 2019-08-21 at 11 19 39 AM](https://user-images.githubusercontent.com/28388782/63411042-b7db6480-c405-11e9-9a14-8092af2f7ccb.png)

**Desktop (please complete the following information):**
i am running the archerysec in docker using the docker-compose provided in your repo.

**Additional context**

**Comment by anandtiwarics** [comment]
Hi,

I think you are using an older version of Clair. I've fixed the parser, please check and confirm.

**Comment by mulakkalfaizal** [comment]
can you please provide me a working clair json report (json file) so i can test.

in my project i am using arminc/clair-local-scan to clair. but i can see that in the original clair docs it produce html report . how can i import clair html report to archerysec ?
