### ISSUE TITLE
Is there any provision for HOST mapping in Archery ?

### ISSUE THREAD

**Issue by bansalani** [archerysec/archerysec#32]
I am trying to deploy Archery and I was hoping if there is anyway I could do Host Mapping specifically for Archery. 
I am using docker image to run Archery
Also I want to know if Git update and Docker image update for Archery happen at the same time ?

## STEPS TO REPRODUCE THE ISSUE

```
1. This is the first step
2. This is the second step
3. Further steps, etc.
```

## CONSOLE OUTPUT

```
Paste the output generated at your console/terminal while scanning the mobile app.
The console log should contain the error or bug you are seeing
(NOT REQUIRED FOR FEATURE REQUEST/ENHANCEMENT)
```

**Comment by anandtiwarics** [comment]
Hi,

Sorry currently its not supporting  your requirements but will figure it out later. 

Thanks.
