### ISSUE TITLE
report upload parse error

### ISSUE THREAD

**Issue by nocomp** [archerysec/archerysec#320]
hi,
i am running a docker version in persistant mode, and whatever type of report, xml or html i always get an error when i try to upload a burp report file either in htm or xml

Request Method: | POST
-- | --
http://localhost:8000/webscanners/xml_upload
1.11.23
ParseError
mismatched tag: line 81, column 106
/usr/lib/python2.7/xml/etree/ElementTree.py in _raiseerror, line 1523
/usr/bin/python
2.7.15
['/home/archerysec/app',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/home/archerysec/.local/lib/python2.7/site-packages',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf']
Fri, 6 Sep 2019 08:47:33 +0000

any idea what i could check?
thxx for your time

**Comment by nocomp** [comment]
more infos:
-------------------------------

Request Method: | POST
-- | --
http://localhost:8000/webscanners/xml_upload
1.11.23
ParseError
mismatched tag: line 81, column 106
/usr/lib/python2.7/xml/etree/ElementTree.py in _raiseerror, line 1523
/usr/bin/python
2.7.15
['/home/archerysec/app',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/home/archerysec/.local/lib/python2.7/site-packages',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf',  '/home/archerysec/.local/lib/python2.7/site-packages/odf']
Fri, 6 Sep 2019 08:47:33 +0000

**Comment by nocomp** [comment]
Variable | Value
-- | --
scan_url | u'87.252.12.11'
csrfmiddlewaretoken | u'eRzxK3ZaaImJosVgRVRhwTaM85w5kuId5T0M5nSP3FVwXFKDIIdolSUH8AS3d37a'
project_id | u'ec381df6-a105-4082-957f-d54d69d687e1'
scanner | u'burp_scan'

FILES
Variable	Value
xmlfile	
<InMemoryUploadedFile: hte.html (text/html)>

Variable | Value
-- | --
CONTENT_LENGTH | '29341'
CONTENT_TYPE | 'multipart/form-data; boundary=----WebKitFormBoundaryhVPO3jU3AnsPDRqw'
CSRF_COOKIE | 'k2B382P9tfiymQHiqCnKgQF346rD00k9b42itmIOmcRlV3wFhpJR5PpY4BNBTzJ6'
DJANGO_SETTINGS_MODULE | 'archerysecurity.settings.base'
GATEWAY_INTERFACE | 'CGI/1.1'
HOME | '/home/archerysec'
HOSTNAME | '5c5c49de443b'
HTTP_ACCEPT | 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3'
HTTP_ACCEPT_ENCODING | 'gzip, deflate, br'
HTTP_ACCEPT_LANGUAGE | 'fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7'
HTTP_CACHE_CONTROL | 'max-age=0'
HTTP_CONNECTION | 'keep-alive'
HTTP_COOKIE | 'PHPSESSID=nsjpe009qhu3jnsttdblgi4cs6; security_level=0; remember_user_token=BAhbCFsGaQZJIiIkMmEkMTAkcktYdUFjVEdpTFVwY0JDcjVZamhUZQY6BkVUSSIXMTU2NzUxMzA4NC4zNjI4MzY4BjsARg%3D%3D--2c8385a3b4fc1e97eabe83e87df891a6097f17bd; _arachni_webui_session=TXJnNEcwRDZKcGUzcURTc3doS29WSlE2T0hYVkh3WGpnUFNjS0NLYnN5Q0FBVkNCUG4wTlcvUloyR0tHMDRzc1VEamZzdGFlRHIveTFrVUs0cnNRdkQ2QmQzWjQyb0JNY0pOM3pWUHAzQ1UvQWRrTzlOc0Zsall1a3VKUTIvZDZ4UGtFYW8vd25oVHMzdEk2a1B5QnlORlNsdkZkU0xMZmg2ZnJiaW5XTUN3QUxvYjhXZVM3aGxJa0ZKbGVWN3hLR0lSL0tzT2dQYTdyUFExVEUvSThBQytJSTlQYjBoOVJVNHhWUTVFRC96RHdZWmljanRSMGF0UlMraElpL1RKczRGY2E1YjBTdy9VV0ZvZTBLZVM0b25EVVAzNldiRk5DLzk4UXlGcFFIZXBvaGNEVkFybE0zOS8rNGZlbGtkajUtLXNrWFVlTE93UmNWZnZjVlVKYkNZb2c9PQ%3D%3D--45e3222c44ff8f801240eaf84f55819536719074; session=.eJw9UEtrg0AQ_itlzzkkJl6EHAIrIYGdxbAqMxdpfbDOagvaYtyQ_95tDj3Ox3zPh6i6qZ2tSLr3YW43ouobkTzE24dIBJqGwZNDj3fgekEGiyZf0JBTPluBcVFRHhOfvC4LS_I2KoNbbbII2A5oikGN117JdAf-EpGsY-TsoE29wvniIXDB5F5LF7DB6VLFypAN_JWYLHK-0lj0GN16-LvL4M0ueOFKUnkyzYBch9_sKJ4bUc9TV31_ufbzvwIZF6Lne4xoJJnuQWYHOiuvz-kWQzUy9T3IsJbXkUqwAV_gdHzJ_czt9JpD7MTzF7yHY9w.XW9kJw.deN66dH47DCVe6k4wH_7EEu7cAQ; currentComponent=webshell; csrftoken=k2B382P9tfiymQHiqCnKgQF346rD00k9b42itmIOmcRlV3wFhpJR5PpY4BNBTzJ6; sessionid=7zjct1foxzn3ecks4qi5zbtv1mqx1yhd; messages="e6fb2d6d09f39da7e6c575a331db8cc8165ef1fa$[[\\"__json_message\\"\\0540\\05425\\054\\"Project Created\\"]]"'
HTTP_HOST | 'localhost:8000'
HTTP_ORIGIN | 'http://localhost:8000'
HTTP_REFERER | 'http://localhost:8000/webscanners/xml_upload'
HTTP_SEC_FETCH_MODE | 'navigate'
HTTP_SEC_FETCH_SITE | 'same-origin'
HTTP_SEC_FETCH_USER | '?1'
HTTP_UPGRADE_INSECURE_REQUESTS | '1'
HTTP_USER_AGENT | 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36'
PATH | '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
PATH_INFO | u'/webscanners/xml_upload'
PWD | '/home/archerysec/app'
QUERY_STRING | ''
REMOTE_ADDR | '172.17.0.1'
REMOTE_HOST | ''
REQUEST_METHOD | 'POST'
RUN_MAIN | 'true'
SCRIPT_NAME | u''
SERVER_NAME | '5c5c49de443b'
SERVER_PORT | '8000'
SERVER_PROTOCOL | 'HTTP/1.1'
SERVER_SOFTWARE | 'WSGIServer/0.1 Python/2.7.15+'
SHLVL | '1'
TERM | 'xterm'
TZ | 'UTC'
_ | '/usr/bin/python'
wsgi.errors | <open file '<stderr>', mode 'w' at 0x7f78a66431e0>
wsgi.file_wrapper | ''
wsgi.input | <socket._fileobject object at 0x7f789317d9d0>
wsgi.multiprocess | False
wsgi.multithread | True
wsgi.run_once | False
wsgi.url_scheme | 'http'
wsgi.version | (1, 0)

**Comment by nocomp** [comment]
Setting | Value
-- | --
ABSOLUTE_URL_OVERRIDES | {}
ADMINS | []
ALLOWED_HOSTS | ['*']
APPEND_SLASH | True
AUTHENTICATION_BACKENDS | [u'django.contrib.auth.backends.ModelBackend']
AUTH_PASSWORD_VALIDATORS | u'********************'
AUTH_USER_MODEL | u'auth.User'
BACKGROUND_TASK_RUN_ASYNC | True
BASE_DIR | '/home/archerysec/app/archerysecurity/..'
CACHES | {u'default': {u'BACKEND': u'django.core.cache.backends.locmem.LocMemCache'}}
CACHE_MIDDLEWARE_ALIAS | u'default'
CACHE_MIDDLEWARE_KEY_PREFIX | u'********************'
CACHE_MIDDLEWARE_SECONDS | 600
CRYPTOGRAPHY_BACKEND | <cryptography.hazmat.backends.openssl.backend.Backend object at 0x7f78a09cbad0>
CRYPTOGRAPHY_DIGEST | <cryptography.hazmat.primitives.hashes.SHA256 object at 0x7f78946c87d0>
CRYPTOGRAPHY_KEY | u'********************'
CRYPTOGRAPHY_SALT | 'django-cryptography'
CSRF_COOKIE_AGE | 31449600
CSRF_COOKIE_DOMAIN | None
CSRF_COOKIE_HTTPONLY | False
CSRF_COOKIE_NAME | u'csrftoken'
CSRF_COOKIE_PATH | u'/'
CSRF_COOKIE_SECURE | False
CSRF_FAILURE_VIEW | u'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME | u'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS | []
CSRF_USE_SESSIONS | False
DATABASES | {'default': {'ATOMIC_REQUESTS': False,              'AUTOCOMMIT': True,              'CONN_MAX_AGE': 0,              'ENGINE': 'django.db.backends.sqlite3',              'HOST': '',              'NAME': '/home/archerysec/app/archerysecurity/../db.sqlite3',              'OPTIONS': {},              'PASSWORD': u'********************',              'PORT': '',              'TEST': {'CHARSET': None,                       'COLLATION': None,                       'MIRROR': None,                       'NAME': None},              'TIME_ZONE': None,              'USER': ''}}
DATABASE_ROUTERS | []
DATA_UPLOAD_MAX_MEMORY_SIZE | 5242880
DATA_UPLOAD_MAX_NUMBER_FIELDS | 1000
DATETIME_FORMAT | u'N j, Y, P'
DATETIME_INPUT_FORMATS | [u'%Y-%m-%d %H:%M:%S',  u'%Y-%m-%d %H:%M:%S.%f',  u'%Y-%m-%d %H:%M',  u'%Y-%m-%d',  u'%m/%d/%Y %H:%M:%S',  u'%m/%d/%Y %H:%M:%S.%f',  u'%m/%d/%Y %H:%M',  u'%m/%d/%Y',  u'%m/%d/%y %H:%M:%S',  u'%m/%d/%y %H:%M:%S.%f',  u'%m/%d/%y %H:%M',  u'%m/%d/%y']
DATE_FORMAT | u'N j, Y'
DATE_INPUT_FORMATS | [u'%Y-%m-%d',  u'%m/%d/%Y',  u'%m/%d/%y',  u'%b %d %Y',  u'%b %d, %Y',  u'%d %b %Y',  u'%d %b, %Y',  u'%B %d %Y',  u'%B %d, %Y',  u'%d %B %Y',  u'%d %B, %Y']
DEBUG | True
DEBUG_PROPAGATE_EXCEPTIONS | False
DECIMAL_SEPARATOR | u'.'
DEFAULT_CHARSET | u'utf-8'
DEFAULT_CONTENT_TYPE | u'text/html'
DEFAULT_EXCEPTION_REPORTER_FILTER | u'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE | u'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL | u'webmaster@localhost'
DEFAULT_INDEX_TABLESPACE | u''
DEFAULT_TABLESPACE | u''
DEF_TIME_ZONE | 'UTC'
DISALLOWED_USER_AGENTS | []
DJANGO_NOTIFICATIONS_CONFIG | {'SOFT_DELETE': True}
EMAIL_BACKEND | 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST | None
EMAIL_HOST_PASSWORD | u'********************'
EMAIL_HOST_USER | None
EMAIL_PORT | None
EMAIL_SSL_CERTFILE | None
EMAIL_SSL_KEYFILE | u'********************'
EMAIL_SUBJECT_PREFIX | u'[Django] '
EMAIL_TIMEOUT | None
EMAIL_USE_LOCALTIME | False
EMAIL_USE_SSL | False
EMAIL_USE_TLS | None
FILE_CHARSET | u'utf-8'
FILE_UPLOAD_DIRECTORY_PERMISSIONS | None
FILE_UPLOAD_HANDLERS | [u'django.core.files.uploadhandler.MemoryFileUploadHandler',  u'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE | 2621440
FILE_UPLOAD_PERMISSIONS | None
FILE_UPLOAD_TEMP_DIR | None
FIRST_DAY_OF_WEEK | 0
FIXTURE_DIRS | []
FORCE_SCRIPT_NAME | None
FORMAT_MODULE_PATH | None
FORM_RENDERER | u'django.forms.renderers.DjangoTemplates'
IGNORABLE_404_URLS | []
IMPORT_EXPORT_USE_TRANSACTIONS | True
INSTALLED_APPS | ['archerysecurity',  'rest_framework',  'webscanners',  'projects',  'archerysettings',  'networkscanners',  'staticscanners',  'jiraticketing',  'tools',  'manual_scan',  'django.contrib.admin',  'stronghold',  'django.contrib.auth',  'django.contrib.contenttypes',  'django.contrib.sessions',  'django.contrib.messages',  'django.contrib.staticfiles',  'rest_framework.authtoken',  'debug_toolbar',  'easy_pdf',  'dashboard',  'background_task',  'sitetree',  'import_export',  'vFeedgui',  'compliance',  'notifications']
INTERNAL_IPS | []
LANGUAGES | [(u'af', u'Afrikaans'),  (u'ar', u'Arabic'),  (u'ast', u'Asturian'),  (u'az', u'Azerbaijani'),  (u'bg', u'Bulgarian'),  (u'be', u'Belarusian'),  (u'bn', u'Bengali'),  (u'br', u'Breton'),  (u'bs', u'Bosnian'),  (u'ca', u'Catalan'),  (u'cs', u'Czech'),  (u'cy', u'Welsh'),  (u'da', u'Danish'),  (u'de', u'German'),  (u'dsb', u'Lower Sorbian'),  (u'el', u'Greek'),  (u'en', u'English'),  (u'en-au', u'Australian English'),  (u'en-gb', u'British English'),  (u'eo', u'Esperanto'),  (u'es', u'Spanish'),  (u'es-ar', u'Argentinian Spanish'),  (u'es-co', u'Colombian Spanish'),  (u'es-mx', u'Mexican Spanish'),  (u'es-ni', u'Nicaraguan Spanish'),  (u'es-ve', u'Venezuelan Spanish'),  (u'et', u'Estonian'),  (u'eu', u'Basque'),  (u'fa', u'Persian'),  (u'fi', u'Finnish'),  (u'fr', u'French'),  (u'fy', u'Frisian'),  (u'ga', u'Irish'),  (u'gd', u'Scottish Gaelic'),  (u'gl', u'Galician'),  (u'he', u'Hebrew'),  (u'hi', u'Hindi'),  (u'hr', u'Croatian'),  (u'hsb', u'Upper Sorbian'),  (u'hu', u'Hungarian'),  (u'ia', u'Interlingua'),  (u'id', u'Indonesian'),  (u'io', u'Ido'),  (u'is', u'Icelandic'),  (u'it', u'Italian'),  (u'ja', u'Japanese'),  (u'ka', u'Georgian'),  (u'kk', u'Kazakh'),  (u'km', u'Khmer'),  (u'kn', u'Kannada'),  (u'ko', u'Korean'),  (u'lb', u'Luxembourgish'),  (u'lt', u'Lithuanian'),  (u'lv', u'Latvian'),  (u'mk', u'Macedonian'),  (u'ml', u'Malayalam'),  (u'mn', u'Mongolian'),  (u'mr', u'Marathi'),  (u'my', u'Burmese'),  (u'nb', u'Norwegian Bokm\xe5l'),  (u'ne', u'Nepali'),  (u'nl', u'Dutch'),  (u'nn', u'Norwegian Nynorsk'),  (u'os', u'Ossetic'),  (u'pa', u'Punjabi'),  (u'pl', u'Polish'),  (u'pt', u'Portuguese'),  (u'pt-br', u'Brazilian Portuguese'),  (u'ro', u'Romanian'),  (u'ru', u'Russian'),  (u'sk', u'Slovak'),  (u'sl', u'Slovenian'),  (u'sq', u'Albanian'),  (u'sr', u'Serbian'),  (u'sr-latn', u'Serbian Latin'),  (u'sv', u'Swedish'),  (u'sw', u'Swahili'),  (u'ta', u'Tamil'),  (u'te', u'Telugu'),  (u'th', u'Thai'),  (u'tr', u'Turkish'),  (u'tt', u'Tatar'),  (u'udm', u'Udmurt'),  (u'uk', u'Ukrainian'),  (u'ur', u'Urdu'),  (u'vi', u'Vietnamese'),  (u'zh-hans', u'Simplified Chinese'),  (u'zh-hant', u'Traditional Chinese')]
LANGUAGES_BIDI | [u'he', u'ar', u'fa', u'ur']
LANGUAGE_CODE | 'en-us'
LANGUAGE_COOKIE_AGE | None
LANGUAGE_COOKIE_DOMAIN | None
LANGUAGE_COOKIE_NAME | u'django_language'
LANGUAGE_COOKIE_PATH | u'/'
LOCALE_PATHS | []
LOGGING | {}
LOGGING_CONFIG | u'logging.config.dictConfig'
LOGIN_REDIRECT_URL | '/user/accounts/'
LOGIN_URL | '/login/'
LOGOUT_REDIRECT_URL | None
MANAGERS | []
MEDIA_ROOT | u''
MEDIA_URL | u''
MESSAGE_STORAGE | 'django.contrib.messages.storage.cookie.CookieStorage'
MESSAGE_TAGS | {10: 'alert-info',  20: 'alert-info',  25: 'alert-success',  30: 'alert-warning',  40: 'alert-danger'}
MIDDLEWARE | ['debug_toolbar.middleware.DebugToolbarMiddleware',  'django.middleware.security.SecurityMiddleware',  'stronghold.middleware.LoginRequiredMiddleware',  'django.contrib.sessions.middleware.SessionMiddleware',  'django.middleware.common.CommonMiddleware',  'django.middleware.csrf.CsrfViewMiddleware',  'django.contrib.auth.middleware.AuthenticationMiddleware',  'django.contrib.messages.middleware.MessageMiddleware']
MIDDLEWARE_CLASSES | [u'django.middleware.common.CommonMiddleware',  u'django.middleware.csrf.CsrfViewMiddleware']
MIGRATION_MODULES | {}
MONTH_DAY_FORMAT | u'F j'
NUMBER_GROUPING | 0
PASSWORD_HASHERS | u'********************'
PASSWORD_RESET_TIMEOUT_DAYS | u'********************'
PREPEND_WWW | False
REFRESH_TIMER | 5
REST_FRAMEWORK | {'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework_jwt.authentication.JSONWebTokenAuthentication',                                     'rest_framework.authentication.SessionAuthentication',                                     'rest_framework.authentication.BasicAuthentication'),  'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),  'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning'}
ROOT_URLCONF | 'archerysecurity.urls'
SECRET_KEY | u'********************'
SECURE_BROWSER_XSS_FILTER | False
SECURE_CONTENT_TYPE_NOSNIFF | False
SECURE_HSTS_INCLUDE_SUBDOMAINS | False
SECURE_HSTS_PRELOAD | False
SECURE_HSTS_SECONDS | 0
SECURE_PROXY_SSL_HEADER | None
SECURE_REDIRECT_EXEMPT | []
SECURE_SSL_HOST | None
SECURE_SSL_REDIRECT | False
SERVER_EMAIL | u'root@localhost'
SESSION_CACHE_ALIAS | u'default'
SESSION_COOKIE_AGE | 1209600
SESSION_COOKIE_DOMAIN | None
SESSION_COOKIE_HTTPONLY | True
SESSION_COOKIE_NAME | u'sessionid'
SESSION_COOKIE_PATH | u'/'
SESSION_COOKIE_SECURE | False
SESSION_ENGINE | u'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE | True
SESSION_FILE_PATH | None
SESSION_SAVE_EVERY_REQUEST | False
SESSION_SERIALIZER | u'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_EXPORT | ['REFRESH_TIMER']
SETTINGS_MODULE | 'archerysecurity.settings.base'
SHORT_DATETIME_FORMAT | u'm/d/Y P'
SHORT_DATE_FORMAT | u'm/d/Y'
SIGNING_BACKEND | u'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS | []
STATICFILES_DIRS | []
STATICFILES_FINDERS | [u'django.contrib.staticfiles.finders.FileSystemFinder',  u'django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATICFILES_STORAGE | u'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_ROOT | '/home/archerysec/app/archerysecurity/../static'
STATIC_URL | '/static/'
STRONGHOLD_PUBLIC_URLS | ('^/admin.*?$',  '^/accounts/login/$',  '^/api.*?$',  '^/o.*?$',  '^/api/createuser/$')
TEMPLATES | [{'APP_DIRS': True,   'BACKEND': 'django.template.backends.django.DjangoTemplates',   'DIRS': [],   'OPTIONS': {'context_processors': ['django.template.context_processors.debug',                                      'django.template.context_processors.request',                                      'django.contrib.auth.context_processors.auth',                                      'django.contrib.messages.context_processors.messages',                                      'django_settings_export.settings_export']}}]
TEST_NON_SERIALIZED_APPS | []
TEST_RUNNER | u'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR | u','
TIME_FORMAT | u'P'
TIME_INPUT_FORMATS | [u'%H:%M:%S', u'%H:%M:%S.%f', u'%H:%M']
TIME_ZONE | 'UTC'
USE_ETAGS | False
USE_I18N | True
USE_L10N | True
USE_THOUSAND_SEPARATOR | False
USE_TZ | False
USE_X_FORWARDED_HOST | False
USE_X_FORWARDED_PORT | False
WSGI_APPLICATION | 'archerysecurity.wsgi.application'
X_FRAME_OPTIONS | u'SAMEORIGIN'
YEAR_MONTH_FORMAT | u'F Y'

**Comment by anandtiwarics** [comment]
Please upload burp XML report, also please make sure you have clicked on the check Base64-encode request and response while exporting report.


<img width="639" alt="archery_burp_issue1" src="https://user-images.githubusercontent.com/4271325/64432396-0a8d6f80-d0da-11e9-8792-f81a69796a0f.png">

**Comment by nocomp** [comment]
Yeahhhh works like a charm, but html report still give a parse error when uploading.
Thxx for your time!

**Comment by anandtiwarics** [comment]
Currently, we're not supporting HTML report.
