### ISSUE TITLE
OpenVAS - greenbone gsad : setting not configured

### ISSUE THREAD

**Issue by kraba** [archerysec/archerysec#322]
**Describe the bug**
I'm running RHEL 7 with GreenBone gsad instead of openvas, openvas is no more available:

``Package openvas-9.0.3-6767.el7.art.noarch is obsoleted by greenbone-vulnerability-manager-10.0.0-6947.el7.art.noarch which is already installed``

The gsad is working properly and I tried to setup it to archery:

``Host: localhost/ip address/hostname, port 9392, admin with pass``

but when I'm running a scan nothing appears and I've a new message: "OpenVAS setting not configured"

Is it normal (archery needs openvas) or is something else?
on logs I don't have anything useful
**To Reproduce**
1. Go to settings and configure gsad
2. Click on new scan
3. An alert as "OpenVAS setting not configured" appears

**Expected behavior**
I can run gsad instead of openvas

**Comment by kraba** [comment]
Sorry, as written 

Note that, at this time, Archery generates a TCP connection towards the OpenVAS Manager (not the GSA): therefore, you need to update your OpenVAS Manager configuration to bind this port. Its default port (9390/tcp), but you can update this in your settings.

Is it planned to work?

**Comment by anandtiwarics** [comment]
Can you please run manually scan in OpenVas. Sometime OpenVAS takes time to load the database. Once scans are running fine then try to run through archerysec. 

Please try to run through docker-compose file https://github.com/archerysec/archerysec/blob/master/docker-compose.yml
