### ISSUE TITLE
UnboundLocalError at /jira/submit_jira_ticket/

### ISSUE THREAD

**Issue by overXsky** [archerysec/archerysec#327]
When I create JIRA ticket, it throws an UnboundLocalError.

![微信截图_20191023120016](https://user-images.githubusercontent.com/20083871/67356446-c7edfc80-f58c-11e9-8957-da9cf6c50d8f.png)

**Comment by overXsky** [comment]
Or can someone tell me how to configure JIRA in Archery? Thanks so much.

**Comment by anandtiwarics** [comment]
Go to settings > click on jira setting edit > provide jira cloud URL > username as email id > jira api token 

to get the jira api key please follow > https://confluence.atlassian.com/cloud/api-tokens-938839638.html

![jira](https://user-images.githubusercontent.com/4271325/67388942-3cd62c00-f5b7-11e9-935d-fa2bc7e4599e.png)

let me know if you still getting error.
