### ISSUE TITLE
Bandit report upload parse error

### ISSUE THREAD

**Issue by gibranduatiga** [archerysec/archerysec#328]
hi,
i am running a docker version in persistant mode, and i always get an error when i try to upload a bandit report file either in json or xml

here is the problem:

![alt text](https://i.ibb.co/xfGyCJ0/Screen-Shot-2019-10-24-at-3-25-32-PM.png "IntegrityError")

**Comment by anandtiwarics** [comment]
@gibranduatiga fixed the issue. Please verify from your end.

Note: Please upload JSON file.
