### ISSUE TITLE
Certificate error at https://archerysec.com/

### ISSUE THREAD

**Issue by jose-raul-barreras** [archerysec/archerysec#331]
## EXPLANATION OF THE ISSUE
Can't access to `https://archerysec.com/` using Firefox

## STEPS TO REPRODUCE THE ISSUE

```
1. Go to `https://archerysec.com/`
```

## CONSOLE OUTPUT

```
Did Not Connect: Potential Security Issue

Firefox detected a potential security threat and did not continue to archerysec.com because this website requires a secure connection.

What can you do about it?

archerysec.com has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.
```

**Comment by anandtiwarics** [comment]
use it into incognito mode. maybe it is an issue with browser cache

**Comment by jose-raul-barreras** [comment]
Based on Firefox's error message, the problem is in the certificate:

> Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for archerysec.com. The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io
>  
> Error code: SSL_ERROR_BAD_CERT_DOMAIN
>
