### ISSUE TITLE
Inspec report import isn't working

### ISSUE THREAD

**Issue by efouarge** [archerysec/archerysec#337]
**Describe the bug**
When starting to roll out larger visbility into our single node docker hosts and mesos clusters we're leveraging the CIS Docker Security Inspec tests and they aren't importing correctly.

**To Reproduce**
1. Run an inspec test ie` inspec exec https://github.com/dev-sec/cis-docker-benchmark --reporter json >> /tmp/inspec.json`
2. In ArcherySec import the inspec json to the inspec reporter
3. Stack Trace is thrown

**Expected behavior**
This should import properly, and the data should be represented appropiately in the interface.

**Comment by anandtiwarics** [comment]
@efouarge is it possible for you to share inspec report sample?
