### ISSUE TITLE
upload xml report for find-bugs shows error

### ISSUE THREAD

**Issue by weev3** [archerysec/archerysec#339]
**Describe the bug**
When uploading report from findbugs plugin's output. Archery went wrong. 

**To Reproduce**
1. run the ` findbugs.jar -progress -xml -output report.xml C:\Users\Security\Desktop\JavaVulnerableLab.jar ` command. 
2. upload report.xml to archery web interface.
3. error occured.

**Comment by anandtiwarics** [comment]
@weev3 what findbugs version are you using?
