### ISSUE TITLE
Faied to install on Parrot OS

### ISSUE THREAD

**Issue by hackvice** [archerysec/archerysec#340]
**Describe the bug**
Unable to install on Parrot OS/Kali

**To Reproduce**
1. Go to '...' # Install requirements
pip install -r requirements.txt
2. Click on 'ENTER'
3. Scroll down to 'ERROR'
`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-edkqpu34/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-0wg6irla/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-edkqpu34/cffi/`

**Expected behavior**
Unabe to install.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Parrot OS
Latest

**Additional context**

```
Failed building wheel for cffi
Running setup.py clean for cffi
  Running setup.py bdist_wheel for reportlab ... error
Failed building wheel for reportlab
pylint 1.9.3 has requirement astroid<2.0,>=1.6, but you'll have astroid 2.3.3 which is incompatible.
```

**Comment by anandtiwarics** [comment]
Please follow the below steps.
$ git clone https://github.com/archerysec/archerysec.git
$ cd archerysec
$ ./setup.sh
$ ./run.sh

Note:
Make sure you have below requirements installed
python 3
virtualenv
