### ISSUE TITLE
Dependency error when running the run.sh inside archerysec tool installation folder

### ISSUE THREAD

**Issue by NGURUJI** [archerysec/archerysec#341]
root@saiuser-VirtualBox:/home/saiuser/Downloads/archerysec# ./run.sh 
[2019-12-13 12:07:22 +0530] [5305] [INFO] Starting gunicorn 19.9.0
[2019-12-13 12:07:22 +0530] [5305] [INFO] Listening at: http://0.0.0.0:8000 (5305)
[2019-12-13 12:07:22 +0530] [5305] [INFO] Using worker: threads
[2019-12-13 12:07:22 +0530] [5308] [INFO] Booting worker with pid: 5308
/home/saiuser/Downloads/archerysec/venv/lib/python3.5/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.7) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

**Comment by anandtiwarics** [comment]
Seems it's already running on `http://0.0.0.0:8000`. Please ignore these errors. 
try to access `http://127.0.0.1:8000` in your browser.

**Comment by NGURUJI** [comment]
Thanks Sir

**Comment by aadarshr1** [comment]
Hi Anand,

I followed the tutorial at https://docs.archerysec.com/getting-started/Installation/ and ran these commands on an Ubuntu Virtual Machine. I also got the same error while running the following commands:

python manage.py makemigrations networkscanners
python manage.py makemigrations webscanners
python manage.py makemigrations projects
python manage.py makemigrations APIScan
python manage.py makemigrations osintscan
python manage.py makemigrations jiraticketing

After executing the next set of commands, the server started running on 127.0.0.1:8008. However, I was still unable to access the tool from the browser on my local machine. Please advise.

**Comment by anandtiwarics** [comment]
run below commands & make sure you have python3, pip3 and virtualenv pre installed in your system.
 
```bash
$ git clone https://github.com/archerysec/archerysec.git
$ cd archerysec
$ ./setup.sh
$ ./run.sh
```
access 127.0.0.0:8000 in your browser.

**Comment by aadarshr1** [comment]
Thanks for your response. I installed python3, pip3, virtualenv and then ran the above commands. When I tried running run.sh, it gave the following errors-

1) gunicorn command is not recognized
2) 'futures' package is needed to run with this Python version.

I ran the following commands to install gunicorn and futures:
1) sudo apt-get install gunicorn
2) pip install futures

However, it is still showing me that the 'futures' package is needed. Please advise.
