### ISSUE TITLE
Scan Result from OpenVas is not populated in Archery dashboard after scan completes

### ISSUE THREAD

**Issue by ravi-mrk** [archerysec/archerysec#358]
**Describe the bug**
Scan Result from OpenVas is not populated in Archery dashboard after scan completes

**To Reproduce**
Steps to reproduce the behaviour:
1. Login into Archery tool and enter the Openvas server details in Settings Page.
2. Go to main menu page and click on 'Launch Scans' and click 'Infrastructure Scans'
3. Give the target server and project details, select OpenVas and click 'Launch'
4. After the scan completes, the Scan completion % is shown but the scan results are not populated
5. The logs from the docker container shows below:
`[Scan ID caf0c610-0715-4801-acc6-ad2986a8c73d](Running) Scan progress: 98.0 %
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/archerysec/app/networkscanners/views.py", line 255, in openvas_scanner
    vuln_an_id(scan_id=scan_id, project_id=project_id, username=username)
  File "/home/archerysec/app/scanners/scanner_plugin/network_scanner/openvas_plugin.py", line 249, in vuln_an_id
    dup_data = name + host + severity + port
NameError: name 'name' is not defined`

**Expected behavior**
The scan results from OpenVas must be populated on Archery dashboard like they get shown for ZAP scans.

**Comment by anandtiwarics** [comment]
@ravi-mrk Fixed the issue, please have a look and verify from your end.
