### ISSUE TITLE
nmap vulners error

### ISSUE THREAD

**Issue by telekomancer** [archerysec/archerysec#363]
**When i try to configure nmap vulners from Setting menu doesn nv_details an error occur**

**To Reproduce**
1. Go to 'Login'
2. Click on 'Right upper corner icon'
3. Click on 'Settings'
3. Scroll down to 'NMAP Vulners'
4. Click on 'Edit'
5. Enable all or change some settings
6. Click on 'Save'
7. See the error, the error starts as:
```
ValueError at /networkscanners/nv_details

too many values to unpack (expected 2)
```

**Expected behavior**
Save the settings and able to use nmap

**Screenshots**
![imagen](https://user-images.githubusercontent.com/27900350/83082445-85742d00-a051-11ea-8b96-52b265bf02dc.png)

**Desktop (please complete the following information):**
 - OS: Centos 7, 64b w/ kernel 3.10.0-1127.8.2.el7.x86_64
 - Browser [chrome, firefox]
 - Version [75.0.3770.142 (Build oficial) (64 bits), 68.8.0esr (64-bit)]

**Additional context**
If i change the values directly from db:
```
sqlite3 /home/tools/archerysec/db.sqlite3
sqlite> insert into archerysettings_nmap_vulners_setting_db values (1,1,1,0,5,'admin');
```
Am not able to use nmap neither

**Comment by anandtiwarics** [comment]
@telekomancer fixed this issue, please check from your end.
