### ISSUE TITLE
OpenVAS connection and usage

### ISSUE THREAD

**Issue by telekomancer** [archerysec/archerysec#364]
Similar to case #363, but am able to configure the OpenVAS but not use it, if i enter OpenVAS Scan, i see a notification that shows that OpenVAS isn't configured:

Configuration:
![imagen](https://user-images.githubusercontent.com/27900350/83082727-3975b800-a052-11ea-8672-9f696fca482a.png)

Scan:
![imagen](https://user-images.githubusercontent.com/27900350/83082761-514d3c00-a052-11ea-9818-d34ad3d36cb4.png)

Notification:
![imagen](https://user-images.githubusercontent.com/27900350/83082787-64600c00-a052-11ea-821c-175e8b00df2b.png)

**Comment by anandtiwarics** [comment]
@telekomancer I hope you have followed the [OpenVAS](https://github.com/archerysec/archerysec#openvas) configuration before putting it into the settings page.

Note ** that, at this time, ArcherySec generates a TCP connection towards the OpenVAS Manager (not the GSA): therefore, you need to update your OpenVAS Manager configuration to bind this port. Its default port (9390/tcp), but you can update this in your settings.
