### ISSUE TITLE
Arachni integration

### ISSUE THREAD

**Issue by telekomancer** [archerysec/archerysec#367]
**Arachni integration issues**
When you try to add arachni sec as datasource, the app and log say that connection to arachni isn't found

**To Reproduce**
1. Add properly arachni input (configuration on settings, host and ip port)
2. Click on 'Launch Scans'
3. Scroll down and 'click on arachni'
4. Enter the url to scan and crash

**Expected behavior**
You should be able to enter the datasource, scan and the output of arachni should see at dashboard

**Screenshots**

![imagen](https://user-images.githubusercontent.com/27900350/84207012-5791de00-aa7e-11ea-8935-5f8d231b22b0.png)

![imagen](https://user-images.githubusercontent.com/27900350/84207029-611b4600-aa7e-11ea-97ad-76dce389d996.png)

Log info:

```
[2020-06-09 22:18:42 +0000] [17] [INFO] Handling signal: winch
Arachni Connection Not found
```

**Additional context**
Has [!issue 366](https://github.com/archerysec/archerysec/issues/366) the same problem appears here, and it's a clean install
I forgot to say that if i go to the container and curl the URL of the arachni, it's reachable:

```
archerysec@e2763fad4d75:~/app$ curl -I http://172.16.162.139:9292/d/users/sign_in
HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
ETag: W/"53437928f25521eb5747b72a31b57d8d"
Cache-Control: max-age=0, private, must-revalidate
Set-Cookie: _arachni_webui_session=S205ZFhRRUk0aVBaNWV2TU0vMnFIR25TWnhVTmxpZ0F4RnhzK0FnbWY4SU5BS1FWaDVKVTRMRWYzcWFqbFkxRStkaStaTmFkYzUwdlJsVTBocFZIYUZiSEgrdU1weEkvcVFOcmxBQnByOFlFUVlHdnd3d1o5VUljZUhuRjNPY1U0eU9JR2JRMzVDTE5EM01Zd3NyTzVXWFZCSnl6WHBoRHQxemRkdXJtQ3I2SVEyTW9pd2JPYkVUR2M2SUJpeENtLS10VUltSDk0am1NcGlaYW1NbXpKTmxnPT0%3D--a9ad1690f46bd5a95d83859166424d29f958c680; path=/; HttpOnly
X-Request-Id: 0a90d240-6221-4880-8ec3-d85312d05e49
X-Runtime: 0.022438
Transfer-Encoding: chunked

archerysec@e2763fad4d75:~/app$ 
```

BTW arachni it's installed:

```
wget https://github.com/Arachni/arachni/releases/download/v1.5.1/arachni-1.5.1-0.5.12-linux-x86_64.tar.gz
tar -xf arachni-1.5.1-0.5.12-linux-x86_64.tar.gz
mv arachni-1.5.1-0.5.12/ arachni
arachni_web /home/tools/arachni/bin/arachni_web -o 0.0.0.0
```

**Comment by anandtiwarics** [comment]
Duplicate of #366

**Comment by telekomancer** [comment]
@anandtiwarics a part of this issue it's related to #366 but another part not, the crash it's related to #366 but _Arachni Connection Not found_ isn't related to #366 so please reopen the issue and i'll modify it.

**Comment by telekomancer** [comment]
Any update?

**Comment by anandtiwarics** [comment]
hey @telekomancer, I have identified the source of the issue. Will be resolve soon.

**Comment by telekomancer** [comment]
Thanks so much!

**Comment by anandtiwarics** [comment]
@telekomancer fixed the issue, please verify from your end.

Also, make sure you are running arachni rest server by below command, and settings are correctly configured into archerysec. 

`bin/arachni_rest_server --address 0.0.0.0` 

Below the sample of setting in archerysec.

Provide IP and PORT of arachni inside archerysec settings.

<img width="663" alt="arachni-setting" src="https://user-images.githubusercontent.com/4271325/87405643-5869e280-c5dd-11ea-81a0-57d291d4a4c1.png">

**Comment by telekomancer** [comment]
Now works properly, just a tip, the photo that you attach it's valid for full-install environment or deployments, that doesn't work at docker
