### ISSUE TITLE
Integrate ArcherySec + OWASP ZAP in Jenkins CI/CD Pipeline

### ISSUE THREAD

**Issue by julialamenza** [archerysec/archerysec#370]
**Describe the bug**
When I follow the tutorial from archerysec blog >>Integrate ArcherySec + OWASP ZAP in Jenkins CI/CD Pipeline
If I try to create project, scanid etc manually using archersec_cli I get a BD error in python
"from_db_valir() takes 4 positional arguments but 5 were given"

Also I if I follow the pipeline part I just see as a failure and no data in archery dashboard

**To Reproduce**
follow the tutorial blog
https://blog.archerysec.com/Integrate-ArcherySec-OWASP-ZAP-in-Jenkins-CICD-Pipeline/
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  MC OS Catalina
 - Browser CHROME
 
![WhatsApp Image 2020-06-16 at 19 37 52](https://user-images.githubusercontent.com/1210648/84824143-63017e00-b017-11ea-9ef0-e081c6991fb4.jpeg)
![Uploading WhatsApp Image 2020-06-16 at 19.38.03.jpeg…]()

**Comment by anandtiwarics** [comment]
hey, thanks for reporting to us. I'm looking into this issue, will update you soon.

**Comment by anandtiwarics** [comment]
Duplicate of #366
