### ISSUE TITLE
OpenVAS Setting not configured

### ISSUE THREAD

**Issue by siddharthmishra01** [archerysec/archerysec#371]
Getting "OpenVAS Setting not configured" alert while launching infrastructure scan using OpenVAS.
I am running application using docker-compose.

**To Reproduce**
1. Clone the repo
2. docker-compose up -d
3. configure OpenVAS setting with port 9390 running on the same machine
4. Launch Infrastructure Scan using OpenVAS.

![image](https://user-images.githubusercontent.com/13079722/86537326-fab60600-bf0b-11ea-89a4-198b7bad817f.png)

![image](https://user-images.githubusercontent.com/13079722/86537375-305aef00-bf0c-11ea-8d3a-23537c9d5759.png)

This seemed to me similar to https://github.com/archerysec/archerysec/issues/322

While I am able to run OpenVAS scans manually through UI running on 443 port.

Still i am getting "OpenVAS Setting not configured" alert while launching infrastructure scan using OpenVAS.

**Comment by telekomancer** [comment]
This issue not only apply with `docker-compose`it's also for OpenVAS "Out Of The Box" i mean, if OpenVAS it's on another machine, container local or remote, the pop-up appears always

**Comment by telekomancer** [comment]
do you know @anandtiwarics if this issue can have a solution ?
