### ISSUE TITLE
Setting page crashing 

### ISSUE THREAD

**Issue by mulakkalfaizal** [archerysec/archerysec#372]
**Describe the bug**
Setting page crashing 

**To Reproduce**
1. login to the portal
2. click on the setting from the top right corner
3. See error

**Expected behavior**
setting page should open

**Screenshots**
<img width="850" alt="Screen Shot 2020-07-06 at 11 17 37 PM" src="https://user-images.githubusercontent.com/17142729/86631285-f870ac00-bfde-11ea-9ad9-773cefd915db.png">

**Desktop (please complete the following information):**
 - OS: macos
 - Browserchrome

**Additional context**
I started the application with the docker compose from the master branch

**Comment by anandtiwarics** [comment]
@mulakkalfaizal seems the database has not migrated properly. Please try to install with fresh installation machine.
