### ISSUE TITLE
Api to update the static scan report

### ISSUE THREAD

**Issue by mulakkalfaizal** [archerysec/archerysec#373]
**Is your feature request related to a problem? Please describe.**
Need an API to upload the report of static scan such as Clare, trivy etc.
**Describe the solution you'd like**
Create an API so we can run that from the ci/cd pipeline itself.

If it is already there could you please share an example.

**Comment by anandtiwarics** [comment]
check it out this blog : https://blog.archerysec.com/Integrate-ArcherySec-OWASP-ZAP-in-Jenkins-CICD-Pipeline/
