### ISSUE TITLE
Jira ID

### ISSUE THREAD

**Issue by telekomancer** [archerysec/archerysec#374]
**Jira tickets isn't reflected at Vulnerability list**
Integrate jira with archery, archery creates the ticket but says "None"

**To Reproduce**
Integrate Cloud Jira properly
1. Trigger a scan
2. Take one vulnerability
3. Create a ticket
4. See "error"

**Expected behavior**
Jira ID appears at vulnerability

**Screenshots**

![imagen](https://user-images.githubusercontent.com/27900350/87495516-97b92300-c61f-11ea-8d99-db6752c59393.png)

![imagen](https://user-images.githubusercontent.com/27900350/87495556-abfd2000-c61f-11ea-8321-0b42041a62dd.png)

**Additional context**
Could be a good idea, include jira self-hosted also.

**Comment by anandtiwarics** [comment]
@telekomancer  fixed the issue. Please check from your end and let me know.

Thanks

**Comment by telekomancer** [comment]
Sorry for the delay.

Works Flawless!
