### ISSUE TITLE
Getting error while installation on Windows 10 system

### ISSUE THREAD

**Issue by ganesh2183** [archerysec/archerysec#375]
**Describe the bug**

Getting below error / warning while i try to run the Archerysec tool in Windows 10 system. I use Git Bash to run this application. I have installed Python3, Pip3, Virtualenv. Please help to resolve this issue. Is there any way to install Archerysec tool in Windows 10 ?

**Desktop:**
 - OS: Windows 10 Enterprise 
 - Python version:  Python 3.7.7
- Pip version: pip 20.1.1

**Additional context**
when i run ./setup.sh i see below error message,
_C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.25) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Operations to perform:
  Apply all migrations: admin, archerysettings, auth, authtoken, background_task, compliance, contenttypes, jiraticketing, manual_scan, networkscanners, notifications, projects, sessions, sitetree, staticscanners, tools, webscanners
Running migrations:
  No migrations to apply.
C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.25) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)_

Again we run ./run.sh command i receive below message,

_./run.sh
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\archerysec\venv\Scripts\gunicorn.exe\__main__.py", line 4, in <module>
  File "c:\archerysec\venv\lib\site-packages\gunicorn\app\wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "c:\archerysec\venv\lib\site-packages\gunicorn\app\base.py", line 12, in <module>
    from gunicorn import util
  File "c:\archerysec\venv\lib\site-packages\gunicorn\util.py", line 9, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'_

**Comment by telekomancer** [comment]
I recommend you @ganesh2183 that use docker for windows and test over it ;-) it's easier
