### ISSUE TITLE
Semgrep Integration

### ISSUE THREAD

**Issue by salecharohit** [archerysec/archerysec#377]
**Is your feature request related to a problem? Please describe.**
Add support for ingesting [Semgrep](https://semgrep.dev/) rules in archerysec.

Attaching sample JSON file of Semgrep run on WebGoat for testing purposes

[WebGoat.zip](https://github.com/archerysec/archerysec/files/5001168/WebGoat.zip)

**Comment by salecharohit** [comment]
command used for running semgrep on WebGoat

semgrep --config "https://semgrep.dev/p/r2c" --json | tee WebGoat.json

**Comment by anandtiwarics** [comment]
Duplicate of #16
