### ISSUE TITLE
Getting TypeError at /burpscanner/burp_setting Object of type 'bytes' is not JSON serializable while integrating with Burp Rest API

### ISSUE THREAD

**Issue by 20harshal** [archerysec/archerysec#381]
**Describe the bug**
While integrating with Burp REST API, After adding details of burp getting below error.
Tried on ubuntu 18, 20 and docker image[archerysec/archerysec:latest]

**To Reproduce**
1. Go to "http://<ip>/burpscanner/burp_setting"
2. Enter API KEY, Host IP, Port
3. Save

**Expected behavior**
It should integrate with Burp Pro.

**Screenshots**
![image](https://user-images.githubusercontent.com/42774059/92993037-8e0f4700-f50c-11ea-8875-52bd33dd12f1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu [18,20,Docker Image]
 - Browser Chrome
 - Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by anandtiwarics** [comment]
It was not reproducible and seems everything works fine. Cloud you please follow the below steps and provide some more error logs?

- stop and remove your archerysec container 
- remove archerysec docker image from your system.
 run below commands

```bash 
$ docker pull archerysec/archerysec
$ docker run -it -p 8000:8000 archerysec/archerysec:latest
```

**Comment by 20harshal** [comment]
I have performed above steps as you have stated, Still getting same error on docker image.
It would be better if you provide solution for ubuntu 20 os (Having python3.8 installed in it). attaching logs of both env.

**For Ubuntu 20 (Hosted on os without any docker image):**
Environment:

Request Method: POST
Request URL: http://<IP>/burpscanner/burp_setting

Django Version: 2.1.8
Python Version: 3.8.2
Installed Applications:
['archerysecurity',
 'rest_framework',
 'webscanners',
 'projects',
 'archerysettings',
 'networkscanners',
 'staticscanners',
 'jiraticketing',
 'tools',
 'manual_scan',
 'django.contrib.admin',
 'stronghold',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework.authtoken',
 'debug_toolbar',
 'easy_pdf',
 'dashboard',
 'background_task',
 'sitetree',
 'import_export',
 'vFeedgui',
 'compliance',
 'notifications']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'stronghold.middleware.LoginRequiredMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware']

Traceback:

File "/opt/archerysec/venv/lib/python3.8/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/opt/archerysec/venv/lib/python3.8/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "/opt/archerysec/venv/lib/python3.8/site-packages/django/core/handlers/base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/archerysec/webscanners/burpscanner/views.py" in burp_setting
  81.         json_issue_data = json.dumps(issue_list.data)

File "/usr/lib/python3.8/json/__init__.py" in dumps
  231.         return _default_encoder.encode(obj)

File "/usr/lib/python3.8/json/encoder.py" in encode
  199.         chunks = self.iterencode(o, _one_shot=True)

File "/usr/lib/python3.8/json/encoder.py" in iterencode
  257.         return _iterencode(o, 0)

File "/usr/lib/python3.8/json/encoder.py" in default
  179.         raise TypeError(f'Object of type {o.__class__.__name__} '

Exception Type: TypeError at /burpscanner/burp_setting
Exception Value: Object of type bytes is not JSON serializable

**For Stand-alone docker instance (The below error we got after following the steps that you have provided)**
Traceback:

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "/home/archerysec/app/venv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/archerysec/app/webscanners/burpscanner/views.py" in burp_setting
  81.         json_issue_data = json.dumps(issue_list.data)

File "/usr/lib/python3.6/json/__init__.py" in dumps
  231.         return _default_encoder.encode(obj)

File "/usr/lib/python3.6/json/encoder.py" in encode
  199.         chunks = self.iterencode(o, _one_shot=True)

File "/usr/lib/python3.6/json/encoder.py" in iterencode
  257.         return _iterencode(o, 0)

File "/usr/lib/python3.6/json/encoder.py" in default
  180.                         o.__class__.__name__)

Exception Type: TypeError at /burpscanner/burp_setting
Exception Value: Object of type 'bytes' is not JSON serializable

**Comment by anandtiwarics** [comment]
I have installed on fresh ubuntu 20 and still not able to reproduce and everything working fine. Could you please try to install on fresh Ubuntu 20.04 and python 3.8 using the following command 

```bash
$ git clone https://github.com/archerysec/archerysec.git
$ cd archerysec
$ ./setup.sh
$ ./run.sh
```

**Comment by 20harshal** [comment]
Tried on fresh Ubuntu 20 and performed installation. Still getting same.
I have my pip freeze output on below link. 
https://raw.githubusercontent.com/20harshal/Test/master/archerysec-pip.txt
Can you provide me yours...!?
Also, What are the correct way to apply burp rest api in archeryesc ?
