### ISSUE TITLE
unable to export burp scan list in any format

### ISSUE THREAD

**Issue by sinnik** [archerysec/archerysec#382]
File "/appl/cicd/products/devsecops/CICD_ArcherySec/venv/lib64/python3.8/site-packages/django/db/models/fields/__init__.py", line 2327, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ["'290061ef-3a92-4b3b-b070-87ac1306c2649d0b96ad-1611-4bdf-b3ee-8787fca0ed6f928fec4a-c1c3-473a-a3a9-5491f12c72443b1d5069-202d-4253-aedc-06ddf703ce43ec5f9e66-0f6e-46cd-9998-b8c58d6a07fa4d2dd0c7-1f3d-4376-a8a4-8ecd60afc9066a312880-d2c9-4680-a4db-87288cfc91f2f3751b65-c656-46fa-aa17-617ac0ff5e875acbc2a9-45bb-473a-8f4d-16bb664b5d1ee3459b46-963c-4dac-9202-15971187e0c0c38bd7b3-ee7f-4617-aa1d-bad90a0ef8c0ff562511-c567-4f15-8abf-da9fbfa41bb462f8e1e1-4cf4-456f-b43e-e869ccadf53e0c3e0d43-cc5b-49ae-8919-4c824110ed301b161ea6-ff3e-4ee7-97a3-46c48cf8b70f9a457269-615f-4e90-b594-50609961cf371709eca5-fad1-414c-93bb-3a2edc1bd92f52c3b98f-2ea6-42aa-aa0f-acb9e713ccbb4294d72c-6ec2-49d5-b9ed-21f3f51b6a3ed75da3f9-0f68-40ad-8090-3260646c3c9e8ce17988-ac01-40cd-b7f3-512abe0a8c9f061726c3-678a-40e2-9b30-be49f7b87a95f2616c23-3fb2-4b3e-9e7b-b56f614039a383243921-5fd1-48f0-a1a0-411e1bb04d413cb0961f-fe71-4525-ae60-d51cf073f62ee95c8575-d80c-47f5-9437-d90281ed175e1517e4e7-cafd-44dd-ad92-31383e29fe388555e27a-e361-44ae-b558-7868a74288cafdcaec61-3722-4af8-a3ff-bab0f6a0b66239e29108-e301-4c64-8495-8d03e242bb6c23f35349-273d-495a-bd5b-004547f18168c76555b8-d059-44c6-a48d-c5631ef6aa8de2e79626-6fad-4267-843e-468859d3a1e2bed0471c-dcb3-470e-a30c-c851e999f000c5cf0731-afc1-49d8-83cc-196e250df0278eb533c8-3bf2-4d01-a57e-cc74c0e4c51a99687ad6-ca27-4180-b8e5-f3f4a747e351f32f49a4-fabc-44e0-ba95-0d9713fc4053c3a79d3e-3b7f-40ad-a514-8afad68dd322df888bd5-3571-4be0-b30a-ecc4b4012cea62377d96-dc15-4d94-97ed-14dcc299fc9f316de8b2-e946-4b26-8184-e20047db30e192336e4c-d7e2-404c-86c0-bb81c65d5b38063ee135-3708-400e-a2f8-c513b37c5fd4166e652f-a42e-4bd4-9776-64bbdffe7a98300e7c87-6adc-420d-ad09-ea76d208006ab3726322-c9aa-447f-b9f5-d5bad389f7fddb2e2c39-bf23-40aa-9acb-8b0bb694efb311d1c6ae-a7fc-4e44-a5bd-380dc3c0a726e04f4a99-0118-4c3b-b32f-a9b4945006d42317ee05-b305-4112-8b08-5a562167ca12b4c7724a-b7a8-48b1-9b57-ad70435d3dfd9903c57b-5916-4db9-8f05-f4fbea63282f25c011f4-71c7-491e-859b-991a1274058d67678020-57f6-4070-8f20-7a438f42b41f4f3a3654-7af4-4cb9-adf2-1e40dac48545a2caeba9-d368-4133-a8fe-47e033a598c3' is not a valid UUID."]
Internal Server Error: /burpscanner/export
Traceback (most recent call last):
  File "/appl/cicd/products/devsecops/CICD_ArcherySec/venv/lib64/python3.8/site-packages/django/db/models/fields/__init__.py", line 2325, in to_python
    return uuid.UUID(value)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/uuid.py", line 169, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

**Comment by anandtiwarics** [comment]
@sinnik Fixed the bug please have a look and let us know

**Comment by sinnik** [comment]
working perfectly thanks Anand
