### ISSUE TITLE
unable to load the dashboard

### ISSUE THREAD

**Issue by sinnik** [archerysec/archerysec#396]
after sign-in the dashboard in not loading up.
command-line error log:
 Not Found: /static/matrix-admin-bt4/dist/css/icons/material-design-iconic-font/css/materialdesignicons.min.css.map
browser errors:
Refused to execute script from '<URL>' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
Uncaught ReferenceError: Chart is not defined
Uncaught TypeError: $(...).DataTable is not a function

**Comment by anandtiwarics** [comment]
is this setup locally or into docker? kindly provide some screenshots and more logs.

**Comment by sinnik** [comment]
running in windows using the setup.bat and run.bat file:
![image](https://user-images.githubusercontent.com/24713972/95727870-68569880-0c98-11eb-8f36-0f1cfa9909b7.png)

![image](https://user-images.githubusercontent.com/24713972/95727966-86bc9400-0c98-11eb-8a57-0aab59dc1343.png)

**Comment by anandtiwarics** [comment]
I think this will not affect the loading of the dashboard. Kindly try clear cached and try again.
