### ISSUE TITLE
Zap Scan report converts all the url to one url.

### ISSUE THREAD

**Issue by sinnik** [archerysec/archerysec#399]
unable to get proper mapping of the zap report and the url mapping.
issue 1:
deleting the scan report doesn't delete the data from postgredb 
table name: webscanners_zap_spider_db

issue 2: after a few refresh hit in the browser the table webscanners_zap_scans_db updates the scan url name with the very first value of the table webscanners_zap_spider_db.
this makes incorrect url and issue mapping.

**Comment by anandtiwarics** [comment]
@sinnik please provide steps to reproduce.

**Comment by sinnik** [comment]
steps to repro:
1 . launch a zap scan.
2. delete the scan.
3. launch a zap scan for different url.
4. refresh the page a few times this will reflect older url name now.
i have emailed you with a video repro the same issue.

**Comment by ashu16815** [comment]
HI Team,

we are facing same issue, Any plans to fix this ? 

Thanks

**Comment by anandtiwarics** [comment]
@sinnik @ashu16815 fixed this issue, please verify from your end.

Thanks
