### ISSUE TITLE
Connection indicators

### ISSUE THREAD

**Issue by lyoko17220** [archerysec/archerysec#40]
**Is your feature request related to a problem? Please describe.**
If you made a bad configuration of your tools. You need to watch python logs to see if it's not ok.

**Describe the solution you'd like**
I think a good idea is to add a indicator for each service to see if the configuration is okay.

**Comment by anandtiwarics** [comment]
Hi @lyoko17220 ,

Thanks for your feedback. We'll look into this and implement python logger to capture logs for each service.

**Comment by httpdss** [comment]
@anandtiwarics also some kind of button on the settings that says "Test Connection" could make its way to see without having to crawl on logs

**Comment by itsgauravjain22** [comment]
This is a must have to implement asap. It would really save time while you have incorrectly enter the details or whether the underlying service is working on somehow crashed. It is also recommended that before launching any scan, archery sec do check whether the underlying service is working and succesfully communicating.
