### ISSUE TITLE
Enable API call for Project Information

### ISSUE THREAD

**Issue by rafaelsilvaa10** [archerysec/archerysec#406]
Hello, i need to get information vulnerabilits by project via API

![image](https://user-images.githubusercontent.com/13574949/96730052-30341180-138c-11eb-9195-0e3604feb0fa.png)

I looked in the documentation and found nothing, is it possible to make this query via API?

I need a sample output

ex: project xpto
      vulnerabilits = 1000
      high = 22
      medium = 531
      low = 99

thanks

**Comment by anandtiwarics** [comment]
Hi, @rafaelsilvaa10 now you can get all information about projects.
