### ISSUE TITLE
Template Docker-compose with full Archerysec tools

### ISSUE THREAD

**Issue by lyoko17220** [archerysec/archerysec#42]
**Is your feature request related to a problem? Please describe.**
I'm working with Archerysec + OpenVas + Burp + Zap. I create a docker-compose to unify all theses component and that's so practical. 

**Describe the solution you'd like**
Create a unify docker-compose template available on Github for all. I can work on it, but the question is if we do that on this repository or not

**Comment by anandtiwarics** [comment]
@lyoko17220 sure will do this. I'm thinking to make dockers for all scanners and connect with each other. This way we no need to individually install scanners into the different systems.

**Comment by lyoko17220** [comment]
Do you want to make a only one repo for all ?

**Comment by lyoko17220** [comment]
Can you create it ? I will work on it this week-end

**Comment by lyoko17220** [comment]
@anandtiwarics Can you create it ? I will work on it this week-end

**Comment by anandtiwarics** [comment]
Done @ https://github.com/archerysec/archerysec/blob/master/docker-compose.yml
