### ISSUE TITLE
DataError at /dashboard/

### ISSUE THREAD

**Issue by jcorremo** [archerysec/archerysec#421]
Archery Scan has been work normally but today  in the morning we are open the web portal and hast a big excepciton "invalid input syntax for integer: ""
LINE 1: ...um", "low", "project_id", "username") VALUES ('', '', '', ''..."

1. Go to 'http://host:port/login'
2. log in to the archery
3. See error

**Expected behavior**
See the dashboards of archery

**Screenshots**
![image](https://user-images.githubusercontent.com/30220845/98694082-0a70ab80-233f-11eb-90f1-0b216b867264.png)

**Additional context**
we are used the archerysec/archerysec:dashboard docker image version

**Comment by anandtiwarics** [comment]
please use `archerysec/archerysec:latest` docker image
