### ISSUE TITLE
clair scan upload not working

### ISSUE THREAD

**Issue by sinnik** [archerysec/archerysec#426]
trying to upload clair scan json report from postman:
![image](https://user-images.githubusercontent.com/24713972/99713002-da0cd800-2ac9-11eb-91dc-ba70e37b3611.png)

even though i get response as success i don't see the report getting uploaded in the archery

**Comment by anandtiwarics** [comment]
could you please share more information like Clair version

**Comment by sinnik** [comment]
clair version 2.1.0 please note the same report upload works from the ui.
is the below body data sufficient for the clair data upload?
![image](https://user-images.githubusercontent.com/24713972/99763401-c771bd80-2b20-11eb-88ec-dda92c2ffcf3.png)

**Comment by anandtiwarics** [comment]
Scanner argument should have clair value insted clair_scan.

I recommend  to use archerysec-cli and you can upload using below command 

`archerysec-cli -s http://127.0.0.1:8000 -u admin -p admin@123 --upload --file_type=JSON --file=../../report\ sample/clair_output.json --TARGET=test --scanner=clair --project_id=a2942e0a-93ae-4de3-aeb3-cdeadfe1f4b6`
