### ISSUE TITLE
Unable to use archery cli auth

### ISSUE THREAD

**Issue by sinnik** [archerysec/archerysec#427]
![image](https://user-images.githubusercontent.com/24713972/100262596-5c861380-2f72-11eb-9673-bc5b1da64217.png)

the same creds works fine in postman and ui login

**Comment by anandtiwarics** [comment]
can you try to create a project using the below command?

`archerysec-cli -s http://127.0.0.1:8000 -u admin -p admin@123 --createproject --project_name=test_project --project_disc="test project"  --project_start=2018-01-11 --project_end=2018-01-11 --project_owner=anand`

**Comment by sinnik** [comment]
getting the same error for the above command as well

**Comment by anandtiwarics** [comment]
I don't see any issue., Kindly check your endpoint server URL and credentials 

<img width="795" alt="archery-issue" src="https://user-images.githubusercontent.com/4271325/100315864-62fea480-2fdf-11eb-8298-a6f805b03695.png">
