### ISSUE TITLE
Dashboard is not loading properly

### ISSUE THREAD

**Issue by v928** [archerysec/archerysec#438]
Hi,
I have installed Archery on Kali Linux and installation looks OK. But after starting the server and visiting the the url dashboard is not loading properly. Getting 404 status in .css and .js file.

GET /login/?next=/ HTTP/1.1" 200 2565
"GET /static/css/bootstrap-responsive.min.css HTTP/1.1" 404 4167
 "GET /static/css/bootstrap.min.css HTTP/1.1" 404 4167
"GET /static/css/archery-login.css HTTP/1.1" 404 4167
 "GET /static/font-awesome/css/font-awesome.css HTTP/1.1" 404 4167
 "GET /static/js/jquery.min.js HTTP/1.1" 404 4167
 "GET /static/js/archery.login.js HTTP/1.1" 404 4167
"GET /static/archery.png HTTP/1.1" 404 4167

Plz help.

Attaching the screenshot of login page.
![archery](https://user-images.githubusercontent.com/44089246/102486043-78bb3300-408e-11eb-879b-571db36e0bc5.JPG)

**Comment by anandtiwarics** [comment]
seems DEBUG is disabled, please run `export DJANGO_DEBUG=1`  before start archerysec
