### ISSUE TITLE
OpenVas

### ISSUE THREAD

**Issue by agentsofshield** [archerysec/archerysec#45]
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/archerysec/networkscanners/views.py", line 144, in openvas_scanner
    scanner = openvas.connect()
  File "/root/archerysec/scanners/scanner_plugin/network_scanner/openvas_plugin.py", line 55, in connect
    str(lod_ov_pass))
  File "/usr/local/lib/python2.7/dist-packages/openvas_lib/__init__.py", line 504, in __init__
    raise VulnscanVersionError("Invalid OpenVAS version in remote server.")
VulnscanVersionError: Invalid OpenVAS version in remote server.
```
I got OpenVas 9 installed... I guess it's the problem but I can't manage to install OpenVas 8 properly.

**Comment by anandtiwarics** [comment]
Hi @agentsofshield,

Recently I update openvas_lib and archery supporting openvas 9 as well. Can you please check which version of openvas_lib you are using. Please make sure openvas_lib 1.1.4 or higher version installed.

```
pip install opevas_lib

```

**Comment by agentsofshield** [comment]
I get this... 
`archerysec 0.1 has requirement openvas-lib==1.1.3, but you'll have openvas-lib 1.1.4 which is incompatible.
`
and I still get that message: "Invalid OpenVas version...".

**Comment by anandtiwarics** [comment]
Please clone the archery master branch `https://github.com/archerysec/archerysec.git` and run latest requirement installation. Should be work. Just I tested and working fine for me. Let me know if you still having an issue.

**Comment by anandtiwarics** [comment]
I'm closing this. Let me know if it's not working.

**Comment by agentsofshield** [comment]
Still getting that message...

**Comment by agentsofshield** [comment]
```
archerysec 0.1 has requirement openvas-lib==1.1.3, but you'll have openvas-lib 1.1.4 which is incompatible.
xhtml2pdf 0.2b1 has requirement html5lib==1.0b10, but you'll have html5lib 1.0.1 which is incompatible.
```
And getting this as well.

**Comment by evgeniysgs3** [comment]
I have a some problems with OpenVAS.
I'm installed it on remote server. Web interface is working. But I don't know how to start openvasmd
netstat -putano
![image](https://user-images.githubusercontent.com/12111054/52373801-38fe7b80-2a21-11e9-8a19-5d3bfee2980b.png)
