### ISSUE TITLE
openvas findings are not reflecting after scan completion 

### ISSUE THREAD

**Issue by praveenDhanaraj** [archerysec/archerysec#461]
Hi, I have integrated archerysec with openvas , infrastructure scan ran for my infra . Reported issue in openvas , after that i checked in archerysec , There is reported only one issue . Its a normal nature of a tool or anything I missed in it . Please some one help me in this .

![image](https://user-images.githubusercontent.com/43632597/113565078-0c0d7980-9628-11eb-9632-b35150aa7546.png)

![image](https://user-images.githubusercontent.com/43632597/113565136-221b3a00-9628-11eb-94d1-83ca1e8ff4dc.png)

Thanks,

**Comment by anandtiwarics** [comment]
@praveenDhanaraj is this directly integrated and scanned through archerysec or just uploaded XML file into archerysec?

**Comment by praveenDhanaraj** [comment]
@anandtiwarics its directly integrated with openvas 
![image](https://user-images.githubusercontent.com/43632597/113575452-809de380-963b-11eb-856d-92ef8fad830f.png)

**Comment by praveenDhanaraj** [comment]
Someone please help me out this issue

**Comment by anandtiwarics** [comment]
@praveenDhanaraj the issue has been fixed now, please verify from your end.
