### ISSUE TITLE
URL Login does not open firefox browser on my machine, if the code is running on server and I access Archery from my machine.

### ISSUE THREAD

**Issue by VarunBhola** [archerysec/archerysec#48]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by anandtiwarics** [comment]
Please install Mozilla selenium driver. https://github.com/mozilla/geckodriver/releases
