### ISSUE TITLE
Was this ever resolved? because i dont see any data on my volume.

### ISSUE THREAD

**Issue by speech1ess** [archerysec/archerysec#489]
Was this ever resolved? because i dont see any data on my volume.

_Originally posted by @carlosmgr in https://github.com/archerysec/archerysec/issues/41#issuecomment-781592469_

i've got the same problem. maybe any updates on this?

**Comment by anandtiwarics** [comment]
you can use the [docker-compose](https://github.com/archerysec/archerysec/blob/master/docker-compose.yml) file and this is the best way to deploy containerize application. Also, you can try [vagrant + ansible](https://github.com/archerysec/archerysec-vagrant-ansible) deployment.
