### ISSUE TITLE
Not able to upload ZAP xml report

### ISSUE THREAD

**Issue by esrkrishna** [archerysec/archerysec#517]
![zap error](https://user-images.githubusercontent.com/37097377/139889420-06ed559b-6e95-41c6-a532-98c75968a3de.PNG)
We are getting "File Not Supported" error while uploading the ZAP xml report 
OWASPZAPReport version="2.11.0"

**To Reproduce**

**Expected behavior**
We are able to upload ZAP sample reports provided by you. but, we are not able to upload OWASPZAP 2.11.0 version xml reports

**Screenshots**

**Desktop (please complete the following information):**
 - Ubunru 20.0
 - Firefox

**Comment by mich4e1** [comment]
Have the same issue!

Do you have any updates how to fix the issue?

**Comment by mich4e1** [comment]
I could found the source of the issue - the new ZAP version is added a few new fields into the XML report format (param, attack, evidence). After deleting the mentioned fields a report was uploaded fine.
<img width="673" alt="image" src="https://user-images.githubusercontent.com/50629340/143031009-e1290c89-b7bd-44d8-ac1d-601b6326edfd.png">


It is required to update the parser in archery.

**Comment by mich4e1** [comment]
@esrkrishna currently I fixed the issue by changing template in ZAP 2.11.0 - without using mentioned new fields.
It is located in <ZAP 2.11.0 Folder>/reports/traditional-xml/report.xml
<img width="816" alt="image" src="https://user-images.githubusercontent.com/50629340/143031389-89ad2ab8-e1ec-4d9f-8f57-7d52ca2bfdc5.png">

**Comment by esrkrishna** [comment]
Namaskaram @mich4e1, 
I have done XML formatting using ATOM XML-formatter plug-in  for manual 
for command line: xml_pp report.xml | sed s|><|>\n<|g 
It is working for me. I am able to upload reports now

**Comment by mich4e1** [comment]
I use ZAP as automated solution for distributed scans, and change one place is easier and faster than changing report on each different place.
It's just my case.

**Comment by esrkrishna** [comment]
Yes @mich4e1, I will also try with your solution, 
Thanks

**Comment by anandtiwarics** [comment]
@esrkrishna @mich4e1 fixed this issue please verify from your end.
