### ISSUE TITLE
Archerysec 8000 port can't Login use variables in docker-compose.yml

### ISSUE THREAD

**Issue by hydgladiator** [archerysec/archerysec#522]
**Describe the bug**
Archerysec can't use IP:8000 default username & password

**To Reproduce**
1. Archersec container is starting OK
2. Use IP:8000 port to login
3. FIle compose.yml  configuration variables have configured in the Archerysec container 
4. But I use configured variable can't not login 8000 port WEB UI 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos7.9]
 - Browser [FireFox , safari]
 

**Additional context**
Have Configured variables in docker-compose.yml
Archerysec

      - DB_PASSWORD=archerysec
      - DB_USER=archerysec
      - DB_NAME=archerysec
      - DB_HOST=db
      - DJANGO_SETTINGS_MODULE=archerysecurity.settings.development
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-"SETME"}
      - DJANGO_DEBUG=1
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - EMAIL=XXX@YYY.com
      - EMAIL_HOST_USER=XXX@YYY.com
      - EMAIL_HOST_PASSWORD='AAAAAA'
      - NAME=XXX
      - PASSWORD='AAAAAA'

Archerysec-worker

  include above, additional
      - ARCHERY_WORKER=True

**Comment by anandtiwarics** [comment]
@hydgladiator fixed this issue please try from your end.

**Comment by hydgladiator** [comment]
Whether If or not I flexed the issue .
I use WEB login 8000 port ,but the username & password which I have configured  in the docker-compose.yml.
Such as EMAIL prefix or NAME/PASSWORD groups that I inputed , but can't  log into through 8000 port.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/13326206/146665467-c998e710-32c1-4dc1-b78a-58bc236bed17.png">

**Comment by anandtiwarics** [comment]
Please make sure you are using email value as username and password for the credential value.

**Comment by hydgladiator** [comment]
I always still on this step .

<img width="590" alt="image" src="https://user-images.githubusercontent.com/13326206/146698510-9cf2cb18-4e8a-418f-a114-074151c91d3d.png">

**Comment by nerodtm** [comment]
what are the default credentials of this login page..
