### ISSUE TITLE
API ERROR

### ISSUE THREAD

**Issue by joksa97** [archerysec/archerysec#534]
**Error when using API**
There is an error when API is used. 

First, in the API documentation, it said to use username and password, but it is needed to use email instead. 

Second when I try to for example create a project it says that URL is not found, when I look to URL defines it says that this is the URL for creating project **api/v1/project-create** not this **/api/project/** . 

Can you give some working examples, because everything that I used from this https://github.com/archerysec/archerysec-python-package is NOT working (only token works) ???

**Screenshots**
![image](https://user-images.githubusercontent.com/18016433/153754214-c6802ca6-ac1a-44f6-8e58-bbe2f0daae99.png)

**Comment by anandtiwarics** [comment]
@joksa97 we have deprecated our old API endpoints and now we'll going to release new endpoints. will keep you updated. Thanks
