### ISSUE TITLE
The Trivy report upload does not work

### ISSUE THREAD

**Issue by Ali-Yazdani** [archerysec/archerysec#542]
**Describe the bug**
The Trivy scan report upload does not work. 

**To Reproduce**
Upload a JSON format Trivy report by web GUI or try to send it by API (Archerysec-cli)

**Comment by CollinNewberry** [comment]
I have this same issue using trivy version 0.27.1.  It appears the json format has changed in the current version of trivy and the parser needs to be updated similar to issue #509 from last October. 
I am currently using:
Trivy version 0.27.1
Archerysec version  2.0.2
Archerysec-cli version 3.1.13
OS Ubuntu 20.04

**Comment by enosonm1505** [comment]
same issue here my trivy report was attached in this commend box 
`{
  "SchemaVersion": 2,
  "ArtifactName": "test1505/test",
  "ArtifactType": "container_image",
  "Metadata": {
    "OS": {
      "Family": "debian",
      "Name": "9.13"
    },
    "ImageID": "sha256:09654f87d08f31bc6bcaba71505defcd6b9e53c077abbe06474a46c9dea62ab8",
    "DiffIDs": [
      "sha256:a75caa09eb1f7d732568c5d54de42819973958589702d415202469a550ffd0ea",
      "sha256:bf1f072b4ddbf4495ca1ea6ad48bbf3b57c479aeb5d04090f14821abf6e7f786",
      "sha256:fa1637ae48b151f418517f3d3002b845ccfbaeed15fc3f070c3f5209d742a4a5",
      "sha256:f7fbe1905fb4925aec80365a805035c9ec6d7cfc79db37121103a35da6427c76",
      "sha256:2847c26f7c041eaabe02d9c65010206c1c4dd3f00d204a02bf67018fadaf7ff6",
      "sha256:3b106ae0c8eee9cac9eeeed671d87def3797b35a26ccdef44a648ee0306e306f",
      "sha256:4d9d004d7e0e2551ae5ba07ab18bd0ab0ae298bc779261c42d1240c96943024f"
    ],
    "RepoTags": [
      "test1505/test:latest"
    ],
    "ImageConfig": {
      "architecture": "amd64",
      "container": "259516e858cf66e0c1ceef0a79ee3e2bddfb9a0cda0914bce909b82d98401f81",
      "created": "2022-06-22T15:00:54.888105373Z",
      "docker_version": "20.10.10",
      "history": [
        {
          "created": "2017-11-04T05:26:40Z",
          "created_by": "/bin/sh -c #(nop) ADD file:a71e077a42995a68ffe4834d85cfe26af4ea12aa8ed43decc03cc487124b1f70 in / "
        },
        {
          "created": "2017-11-04T05:26:40Z",
          "created_by": "/bin/sh -c #(nop)  CMD [\"bash\"]",
          "empty_layer": true
        },
        {
          "created": "2022-06-22T05:44:19Z",
          "created_by": "/bin/sh -c #(nop)  LABEL maintainer=test1505",
          "empty_layer": true
        },
        {
          "created": "2022-06-22T05:51:23Z",
          "created_by": "/bin/sh -c apt-get update \u0026\u0026     apt-get upgrade -y \u0026\u0026     DEBIAN_FRONTEND=noninteractive apt-get install -y     debconf-utils \u0026\u0026     echo mariadb-server mysql-server/root_password password vulnerables | debconf-set-selections \u0026\u0026     echo mariadb-server mysql-server/root_password_again password vulnerables | debconf-set-selections \u0026\u0026     DEBIAN_FRONTEND=noninteractive apt-get install -y     apache2     mariadb-server     php     php-mysql     php-pgsql     php-pear     php-gd     \u0026\u0026     apt-get clean \u0026\u0026     rm -rf /var/lib/apt/lists/*"
        },
        {
          "created": "2022-06-22T15:00:08Z",
          "created_by": "/bin/sh -c #(nop) COPY dir:f09122be2c4cfc983dcc3a741cce3ccb808e688cdc1ff742571463438cda3cf2 in /var/www/html "
        },
        {
          "created": "2022-06-22T15:00:35Z",
          "created_by": "/bin/sh -c chown www-data:www-data -R /var/www/html \u0026\u0026     rm /var/www/html/index.html"
        },
        {
          "created": "2022-06-22T15:00:47Z",
          "created_by": "/bin/sh -c service mysql start \u0026\u0026     sleep 3 \u0026\u0026     mysql -uroot -pvulnerables -e \"CREATE USER app@localhost IDENTIFIED BY 'vulnerables';CREATE DATABASE dvwa;GRANT ALL privileges ON dvwa.* TO 'app'@localhost;\""
`

**Comment by anandtiwarics** [comment]
We have fixed this issue and pushed the code. Please verify from your end. Thanks
