### ISSUE TITLE
Pentest Vulnerability list is empty after adding target 

### ISSUE THREAD

**Issue by kaballero87** [archerysec/archerysec#543]
When you access to Vulnerability list, it is empty, and if you manually add a new vulnerability, it don´t appear in the list.

![unknown_007](https://user-images.githubusercontent.com/96114027/168799677-f4234dfe-ffe8-4c30-9ed9-ae8cefbfec41.png)

**Comment by anandtiwarics** [comment]
how did you add the vulnerability, is it uploading file or by running automated scanner ?

**Comment by kaballero87** [comment]
Uploading files. Do you have any example file for test it again?

**Comment by kaballero87** [comment]
And, if i create a vulnerability like I read in the doc page, the list appears empty too.

**Comment by anandtiwarics** [comment]
which tool/scanner report did you uploaded ?
