### ISSUE TITLE
Automate Jira ticket

### ISSUE THREAD

**Issue by ihangnalli-cci** [archerysec/archerysec#577]
How to automate Jira Ticket creation?
Can we use archerysec-cli?

**Comment by anandtiwarics** [comment]
please make sure Jira is correctly onboarded https://docs.archerysec.com/docs/jira-connector

**Comment by ihangnalli-cci** [comment]
Yes, now I'm getting the option.

But now I'm getting another issue. when I click create a Jira ticket, I'm getting the option of the projects but issue type its not fetching from Jira server. I'm just getting only 2 options for all projects i.e. Bug & Story under issue types. Hence I get this error.
Any Solutions??

![image](https://user-images.githubusercontent.com/115973451/199882558-f2b24726-bd28-4912-93c6-eeddfbcdbc1b.png)

**Comment by ihangnalli-cci** [comment]
There is no option to create a issue, neither its fetching from server.
![image](https://user-images.githubusercontent.com/115973451/200250413-28ab2cbf-ce75-403e-a6d4-d3212b7e6d29.png)

**Comment by anandtiwarics** [comment]
currently, we do not support automated Jira ticket creation
