### ISSUE TITLE
Getting error when setting up an integration with Burp Suite Enterprise

### ISSUE THREAD

**Issue by bahemre** [archerysec/archerysec#586]
Hi, I want to integrate ArcherySec with Burp Suite Enterprise which both of them locate on-prem. These two servers can reach each other. I can reach Burp's API page and all infos are correct. Once I want to integrate, I get an error as shown below.

<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">TypeError at /burpscanner/burp_setting/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Object of type bytes is not JSON serializable</pre>

Request Method: | POST
-- | --
http://ahdast02:8000/burpscanner/burp_setting/
3.2.15
TypeError
Object of type bytes is not JSON serializable
/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/json/encoder.py, line 179, in default
/home/unixamerikan/archerysec/venv/bin/python3.10
3.10.6
['/home/unixamerikan/archerysec',  '/home/unixamerikan/archerysec/venv/bin',  '/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python310.zip',  '/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10',  '/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/lib-dynload',  '/home/unixamerikan/archerysec/venv/lib/python3.10/site-packages',  '/home/unixamerikan/archerysec/venv/lib/python3.10/site-packages/odf',  '/home/unixamerikan/archerysec/venv/lib/python3.10/site-packages/odf',  '/home/unixamerikan/archerysec/venv/lib/python3.10/site-packages/odf',  '/home/unixamerikan/archerysec/venv/lib/python3.10/site-packages/odf',  '/home/unixamerikan/archerysec/venv/lib/python3.10/site-packages/odf',  '/home/unixamerikan/archerysec/venv/lib/python3.10/site-packages/odf',  '/home/unixamerikan/archerysec/venv/lib/python3.10/site-packages/odf']
Tue, 22 Nov 2022 14:26:58 +0300

**Comment by bahemre** [comment]
And this is traceback;

Environment:

Request Method: POST
Request URL: http://ahdast02:8000/burpscanner/burp_setting/

Django Version: 3.2.15
Python Version: 3.10.6
Installed Applications:
['archerysecurity',
 'rest_framework',
 'webscanners',
 'projects',
 'archerysettings',
 'archeryapi',
 'networkscanners',
 'staticscanners',
 'cloudscanners',
 'jiraticketing',
 'cicd',
 'tools',
 'pentest',
 'report_upload',
 'django.contrib.admin',
 'stronghold',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework.authtoken',
 'debug_toolbar',
 'dashboard',
 'background_task',
 'sitetree',
 'import_export',
 'compliance',
 'notifications',
 'user_management',
 'authentication',
 'rest_framework_simplejwt.token_blacklist']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'stronghold.middleware.LoginRequiredMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware']



Traceback (most recent call last):
  File "/home/unixamerikan/archerysec/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/unixamerikan/archerysec/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/unixamerikan/archerysec/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/unixamerikan/archerysec/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/unixamerikan/archerysec/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/unixamerikan/archerysec/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/unixamerikan/archerysec/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/unixamerikan/archerysec/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/unixamerikan/archerysec/webscanners/burpscanner/views.py", line 143, in post
    json_issue_data = json.dumps(issue_list.data)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

Exception Type: TypeError at /burpscanner/burp_setting/
Exception Value: Object of type bytes is not JSON serializable

**Comment by anandtiwarics** [comment]
Hi @bahemre please follow our documentation : https://docs.archerysec.com/docs/burp-connector and let me know if you still getting error

**Comment by bahemre** [comment]
Hi @anandtiwarics Frankly, I think that this page is out of date. Because new version of Burp doesn't have the same screens and settings. For example, API uses port 8080 instead of port 1337. But I understand the point. I've configured Burp API correctly but ArcherySec gives me this error page every time I try to integrate ArcherySec with Burp.

**Comment by anandtiwarics** [comment]
@bahemre what version of burp pro are you using?

**Comment by bahemre** [comment]
Hi @anandtiwarics this is the version; Version: 2022.10-11058, Java version: 17.0.4.
