### ISSUE TITLE
AttributeError: Manager isn't available; 'auth.User' has been swapped for 'user_management.UserProfile

### ISSUE THREAD

**Issue by csakaszamok** [archerysec/archerysec#588]
**Describe the bug**
After a fresh start, cannot login -> "Please check your login details and try again."
..and application log contains an error message:
AttributeError: Manager isn't available; 'auth.User' has been swapped for 'user_management.UserProfile

**To Reproduce**
`
docker pull archerysec/archerysec
docker run -e NAME=user -e EMAIL=user@user.com -e PASSWORD=pass  -it -p  8000:8000 archerysec/archerysec:latest
`
try to login with user/pass

**Expected behavior**
Success to login

**Desktop (please complete the following information):**
Ubuntu 20.04.5 LTS

**Comment by q7hunter** [comment]
so?

**Comment by Voxanimus** [comment]
Hello, sorry to comment this old issue but I encounter the same problem on the docker installation of archery sec. I am completely unable to login into the web interface. If a solution exists I would like to know it.
