### ISSUE TITLE
User of Organisation A can see scans/projects triggered by user in Organisation B

### ISSUE THREAD

**Issue by BarMol3** [archerysec/archerysec#596]
I was having a play around with the Organisations section of the project, and noticed that if you create multiple organisations and run scans as users in those separate organisations, the scans are visible to all users, rather than just the users of the organisation the user who created the project/scan belongs to.

## STEPS TO REPRODUCE THE ISSUE

```
1. Create 2 organisations, and create an admin user in each
2. Log in as each user and create a new project, and trigger a dynamic scan of a URL
3. Notice that when you log into the second user to create the project and scan, the work of the first user is visible to you.
```

**Comment by anandtiwarics** [comment]
Hi, @BarMol3 issue has been fixed. Kindly confirm. Thanks
