### ISSUE TITLE
Code cleanup and  improve coding style.

### ISSUE THREAD

**Issue by anandtiwarics** [archerysec/archerysec#6]
The code should look readable and manageable. Separate folders, split views, a separate folder for the scanners plugin and parsers. Need improvement in Models file.

**Comment by anandtiwarics** [comment]
# 63a62ac 
- Separate forder for scanners plugin.
- Added header

**Comment by httpdss** [comment]
@anandtiwarics I would like to do a heavy cleanup of templates: avoid repeating html, use partials, use of static template tags, make dynamic menus with underlaying logic, etc

starting point for this would be the Dashboard module. are you ok with this?

**Comment by anandtiwarics** [comment]
hey @httpdss sure. We should do this and even I'm also, thinking about changes in templates. Thanks.

**Comment by httpdss** [comment]
perfect @anandtiwarics , let me start with dashboard, and from then on any template change would be even easier.

**Comment by anandtiwarics** [comment]
hi @httpdss I'm planning to switch UI to bootstrap 4 using [matrix-admin-bt4 free](https://wrappixel.com/demos/free-admin-templates/matrix-admin-bt4/html/ltr/index.html). Let me know your thoughts. You can download from [https://matrixadmin.wrappixel.com/](https://matrixadmin.wrappixel.com/)

**Comment by httpdss** [comment]
@anandtiwarics nice! lets talk about this and figure out a roadmap to execute on this changes
