### ISSUE TITLE
Is this project maintained ?

### ISSUE THREAD

**Issue by sticky-note** [archerysec/archerysec#628]
**Describe the bug**
8  months without a release ?

Unable parse Gitlab SAST scan report correctly :
Vuln name is diaplayed as "Not Found"

**To Reproduce**
Upload a Gitlab SAST scan report which contains:
```
{
  "version": "15.0.7",
  "vulnerabilities": [
    {
      "id": "...",
      "category": "sast",
      "name": "...",
      "description": "...",
      "cve": "semgrep_id:bandit.Bxxx:x:x",
      "severity": "Medium",
      "scanner": {
        "id": "semgrep",
        "name": "Semgrep"
      },
      "location": {
        "file": "location.py",
        "start_line": xxx
      },
      "identifiers": [
        {
          "type": "semgrep_id",
          "name": "bandit.BXXX",
          "value": "bandit.BXXX",
          "url": "https://semgrep.dev/r/gitlab.bandit.BXXX"
        },
        {
          "type": "cwe",
          "name": "CWE-xxx",
          "value": "xxx",
          "url": "https://cwe.mitre.org/data/definitions/xxx.html"
        },
        {
          "type": "bandit_test_id",
          "name": "Bandit Test ID BXXX",
          "value": "BXXX"
        }
      ]
    },
    (...)
```

**Expected behavior**
Vuln should be correctly displayed on GUI

**Screenshots**

**Desktop (please complete the following information):**
Not related

**Smartphone (please complete the following information):**
Not related

**Additional context**

**Comment by anandtiwarics** [comment]
Ofcourse YES. currently we support below gitlab stast version https://github.com/archerysec/report-sample/blob/main/Gitlab/gitlab-sast-report-sample.json.
