### ISSUE TITLE
no success/failure indication in all procedures

### ISSUE THREAD

**Issue by stasvolf** [archerysec/archerysec#63]
hello,

during my play with the system i have found that in some places (like re-scan) there is an indication(popup) after performing the action and some functionalities it is missing.

for example when launching a new scan after pressing on "launch" nothing happens regarding the UI.
i have expected to get notified with "Success" message and relevant redirection.

thanks.

**Comment by anandtiwarics** [comment]
Thanks. We'll work on this.

**Comment by faichelbaum** [comment]
Hi @stasvolf 

I added a couple of indicators for the IP and Domain scan forms. 

Just in case
