### ISSUE TITLE
getting webpage error is  ParseError at /webscanners/xml_upload while uploading zap report

### ISSUE THREAD

**Issue by sateesh0584** [archerysec/archerysec#634]
getting webpage error is  ParseError at /webscanners/xml_upload while uploading zap report.
<img width="956" alt="image-20240209-111936" src="https://github.com/archerysec/archerysec/assets/143077082/13845c1d-9670-47ce-be09-0b51f7735885">

If any one have solution let me know.

**Comment by sateesh0584** [comment]
Iam using  Owasp Zap 2.14.0 version

**Comment by sateesh0584** [comment]
> may I know the version of owasp zap ?

Iam using Owasp Zap 2.14.0 version

**Comment by anandtiwarics** [comment]
it working fine. Feel free to re-open and provide more info
