### ISSUE TITLE
Failed to get ZAProxy via Docker

### ISSUE THREAD

**Issue by sandeepjak2007** [archerysec/archerysec#637]
**Describe the bug**

**To Reproduce**
1. Go to the Docker file in the main project file
2. Run the docker file.
3. Error in line wget "https://github.com/zaproxy/zaproxy/releases/download/2.7.0/ZAP_2.7.0_Linux.tar.gz"

**Comment by Lercas** [comment]
If you run the docker compose file, you need to replace `owasp/zap2docker-stable` with the ZAP image `zaproxy/zap-stable`.

If you run dockerfile, change the link to a valid `https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz` and replace everything in the file with valid names

**Comment by anandtiwarics** [comment]
Fixed
