### ISSUE TITLE
Error in Running command in Docker file in project folder

### ISSUE THREAD

**Issue by sandeepjak2007** [archerysec/archerysec#638]
Describe the bug

To Reproduce

1. Go to the Docker file in the main project file
2. Run the docker file.
3. Error in running line no 85 in Docker file in main project folder. Issue attached.
<img width="500" alt="Screenshot 2024-02-25 at 9 56 59 AM" src="https://github.com/archerysec/archerysec/assets/16497904/450febfa-90a1-4afa-8a11-d9afab4f5b4e">

**Comment by anandtiwarics** [comment]
Fixed. Please check
