### ISSUE TITLE
CSRF verification failed

### ISSUE THREAD

**Issue by AndreyPushkinA** [archerysec/archerysec#662]
I'm running Archerysec in docker-compose, on a local_ip:8000 everything works fine, but when I'm trying to use Nginx with domain after log-in it tells me that CSRF verification failed. I was trying to add CSRF_TRUSTED_ORIGINS as it's a Django application in environment variable in docker compose but have no success

**Comment by anandtiwarics** [comment]
we have implemented CROS. Try to add your Nginx domain

https://github.com/archerysec/archerysec/blob/6a0689b712864e92ab11183bfe4c1d35c51ad3b0/archerysecurity/settings/base.py#L236-L239C2

```
CORS_ALLOWED_ORIGINS = [
    'http://localhost:4200',  # Add your Angular application's URL
    # Other allowed origins...
]
```
