### ISSUE TITLE
VulnscanServerError: Connection refused (OpenVAS)

### ISSUE THREAD

**Issue by Xeyk** [archerysec/archerysec#67]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/nf3985/archerysec/networkscanners/views.py", line 177, in openvas_scanner
    scanner = openvas.connect()
  File "/home/nf3985/archerysec/scanners/scanner_plugin/network_scanner/openvas_plugin.py", line 56, in connect
    str(lod_ov_pass))
  File "/usr/lib/python2.7/site-packages/openvas_lib/__init__.py", line 511, in __init__
    raise VulnscanServerError("Error while connecting to the server: %s" % e.message)
VulnscanServerError: Error while connecting to the server: [Errno 111] Connection refused

 - OS: CentOS7

I keep getting this even though I have Archerysec installed on the same server as OpenVas. I have verified correct username and password for admin as I am able to log in with GSAD. 

I have tried using 127.0.0.1, localhost, 0.0.0.0, 10.0.1.15 (internal IP of server) but have not had any luck. Have you seen anyone have this issue before?

**Comment by anandtiwarics** [comment]
which version of OpenVAS are you using?

**Comment by faichelbaum** [comment]
Hi

As I'm having the same error with a server using Ubuntu 16.04 and official deb packages:

> ii  openvas9                              7.0.3-1                                    amd64        remote network security auditor - metapackage
> ii  openvas9-cli                          1.4.5-1xenial                              amd64        remote network security auditor - cli
> ii  openvas9-gsa                          7.0.3-1xenial2                             amd64        remote network security auditor - web interface
> ii  openvas9-manager                      7.0.3-1                                    amd64        remote network security auditor - manager
> ii  openvas9-scanner                      5.1.2-1                                    amd64        remote network security auditor - scanner
>

**Comment by faichelbaum** [comment]
Ok so, OpenVAS9 (version 7.0.3) on Ubuntu only use a socket file by default.
You need to explicitly update your OpenVAS Manager (not GSA) configuration to bind the default port (9390) and only that one
i.e. on Ubuntu, it's via /etc/default/openvas-manager:

> # Defaults for OpenVAS Manager initscript
> # sourced by /etc/init.d/openvas-manager
> # installed at /etc/default/openvas-manager by the maintainer scripts
> 
> # For more information see `man openvasmd`
> 
> # To set listening address:
> # 
> LISTEN_ADDRESS="0.0.0.0"
> 
> # To set listening port number:
> #
> PORT_NUMBER=9390
>

**Comment by anandtiwarics** [comment]
Hi @faichelbaum,

Thanks for your feedback. Is it possible for you to update the README file and create a pull request? 

I really appreciate your contribution to the project and I hope you would help us in the future too.

**Comment by faichelbaum** [comment]
@Xeyk the last PR that got merge will fix your issue:

- more explicit about the OpenVAS daemon
- possibility to change the TCP port

**Comment by Xeyk** [comment]
Sorry about the late response, guys. I had to put this project on hold at work for a while.
@anandtiwarics - I am running openvas 9

@faichelbaum - It looks like I'm still getting the error after updating. Here is the latest message:

`Scan Launched IP: 10.0.1.147
[05/Sep/2018 14:06:22] "POST /networkscanners/launch_scan/ HTTP/1.1" 200 14161
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/nf3985/archerysec/networkscanners/views.py", line 178, in openvas_scanner
    scanner = openvas.connect()
  File "/home/nf3985/archerysec/scanners/scanner_plugin/network_scanner/openvas_plugin.py", line 59, in connect
    int(lod_ov_port))
  File "/usr/lib/python2.7/site-packages/openvas_lib/__init__.py", line 511, in __init__
    raise VulnscanServerError("Error while connecting to the server: %s" % e.message)
VulnscanServerError: Error while connecting to the server: [Errno 111] Connection refused`


Here's a pic of my openvas settings. I made new user through openvasmd called "archery" with admin rights. Openvas and Archery are running on the same server.
[https://i.imgur.com/9lrOMqr.png](url)

**Comment by faichelbaum** [comment]
Can you share your OpenVAS manager configuration (not the GSA one)

**Comment by anandtiwarics** [comment]
@Xeyk Please use docker-compose. Updated docker-compose.yml file which would allow you to create a OpenVAS & ZAP scanner.

**Comment by evgeniysgs3** [comment]
Please help me. I don't know how do me:
![image](https://user-images.githubusercontent.com/12111054/52374962-2b96c080-2a24-11e9-92b6-abbfe9ef157a.png)
I'm rewrite settings in file /etc/default/openvas-manager and openvasmd --rebuild
