### ISSUE TITLE
ZAP scanner runs successfully, but Archerysec does not report any information.

### ISSUE THREAD

**Issue by Xeyk** [archerysec/archerysec#68]
![image](https://user-images.githubusercontent.com/7152014/44097746-bc6f6f76-9f9b-11e8-8fe0-3ed8a8fdef7c.png)

`
Scanning Target https://xxxxxxx.org

ZAP Scan Status: 0

ZAP Scan Status: 1

ZAP Scan Status: 6

ZAP Scan Status: 28

ZAP Scan Status: 44

Scan Completed
`

It looks like the scan completes, but in Archerysec, there are no scans available, and nothing listed anywhere that shows I even started a scan. I feel like I am doing something very wrong, but I am not sure what it could be. Scan was initiated from Archerysec interface under Scan < Domain with ZAP radio button ticked.

**Comment by anandtiwarics** [comment]
this is not a normal behavior and should be listed down in scan list after scan completion. Could you please re-launch the scan and check the output on the console.

Let me know the output log and I'll try resolve it.

**Comment by faichelbaum** [comment]
Hi @anandtiwarics 

which console output are you looking for ? 
Post scan, here is the result:

> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: com
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: targets:----- http://XXXXXXXXXX
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: Spider Completed
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: Scanning Target http://XXXXXXXXXX
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: [u"'null' is not a valid UUID."]
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: ZAP Scan Status: 0
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: ZAP Scan Status: 5
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: ZAP Scan Status: 16
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: ZAP Scan Status: 33
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: ZAP Scan Status: 38
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: ZAP Scan Status: 46
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: ZAP Scan Status: 51
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: ZAP Scan Status: 63
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: ZAP Scan Status: 76
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: ZAP Scan Status: 85
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: message repeated 5 times: [ ZAP Scan Status: 85]
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: ZAP Scan Status: 88
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: message repeated 4 times: [ ZAP Scan Status: 88]
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: ZAP Scan Status: 89
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: message repeated 5 times: [ ZAP Scan Status: 89]
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: Scan Completed
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: http://XXXXXXXXXX
> Aug 21 07:39:20 OVHEU-IT-PRN-SEC-AUDIT archery[22882]: [Errno 2] No such file or directory
>
