### ISSUE TITLE
Page not found (404)

### ISSUE THREAD

**Issue by tao3323225** [archerysec/archerysec#77]
I upload one acunetix report,and i click the button of "Action".Then it show ：

Page not found (404)
Request Method: | GET
http://127.0.0.1:8000/webscanners/acunetix_vuln_list?scan_id=6b18a06d-bacd-4b92-9bf9-265d56ddaa3a

Using the URLconf defined in archerysecurity.urls, Django tried these URL patterns, in this order:

1.admin/
2.webscanners/ ^login/$ [name='login']
3.webscanners/ ^signup/$ [name='signup']
... ...
The current path, webscanners/acunetix_vuln_list, didn't match any of these.

**Comment by anandtiwarics** [comment]
Hi,

Please check you have selected correct scanner from the drop-down menu.

<img width="668" alt="archery 2018-08-31 14-46-26" src="https://user-images.githubusercontent.com/4271325/44904471-07c0a780-ad2d-11e8-9617-e6fefbf2b1b0.png">

**Comment by tao3323225** [comment]
I have successfully uploaded the XML file, and I can see the number of vulnerabilities.

**Comment by tao3323225** [comment]
i click the button of "Action",it still show the error.

**Comment by tao3323225** [comment]
s
![ttt](https://user-images.githubusercontent.com/16127064/44905363-74936c00-ad44-11e8-86fb-9f1ac2456e99.png)

**Comment by tao3323225** [comment]
![qqq](https://user-images.githubusercontent.com/16127064/44905444-a4db0a80-ad44-11e8-96ed-80950ebcc560.png)

**Comment by anandtiwarics** [comment]
Thanks for reporting the issue. I have updated the correct URL.

**Comment by tao3323225** [comment]
great!
Now i need to repull and rebuild ?

**Comment by anandtiwarics** [comment]
no just git pull from the archerysec folder. Should be work fine.

**Comment by tao3323225** [comment]
I tried again, but still ...
I repeat the following steps:
$ docker pull archerysec/archerysec
$ docker run -it -p 8000:8000 archerysec/archerysec:latest

**Comment by anandtiwarics** [comment]
please re-run docker pull archerysec/archerysec. Just updated the docker.

**Comment by tao3323225** [comment]
y,I do "docker pull archerysec/archerysec",but the same....
