### ISSUE TITLE
OperationalError at /webscanners/setting/

### ISSUE THREAD

**Issue by v928** [archerysec/archerysec#83]
Hi,
Installed archery on kali linux without any error. Everything is working fine, but when navigating to http://127.0.0.1:8008/webscanners/setting/ , it gives internal server error.

Pl help.

OperationalError at /webscanners/setting/

no such table: archerysettings_openvas_setting_db

Request Method: 	GET
Request URL: 	http://127.0.0.1:8008/webscanners/setting/
Django Version: 	1.11.16
Exception Type: 	OperationalError
Exception Value: 	

no such table: archerysettings_openvas_setting_db

Exception Location: 	/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py in execute_sql, line 899
Python Executable: 	/usr/bin/python
Python Version: 	2.7.14
Python Path: 	

['/root/archerysec',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/python2.7/dist-packages/wx-3.0-gtk2']

Server time: 	Fri, 12 Oct 2018 11:14:24 +0000

**Comment by anandtiwarics** [comment]
Seems that database has not been migrated. Please run below commands.

<pre>
python manage.py makemigrations networkscanners
python manage.py makemigrations webscanners
python manage.py makemigrations projects
python manage.py makemigrations APIScan
python manage.py makemigrations osintscan
python manage.py makemigrations jiraticketing
python manage.py makemigrations tools
python manage.py makemigrations manual_scan
python manage.py makemigrations archerysettings
python manage.py makemigrations staticscanners
python manage.py migrate
</pre>

**Comment by v928** [comment]
Thanks Anand 

Now working fine.

**Comment by daniejstriata** [comment]
Why are there more databases to migrate here than in the install guide? Before I ran this I could not go to the settings page and some of the other. Running the above fixed my new install on kali.
