### ISSUE TITLE
Zap Scanner is not working 

### ISSUE THREAD

**Issue by v928** [archerysec/archerysec#84]
Targets - test.co.in
Internal Server Error: /zapscanner/zap_scan/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/archerysec/webscanners/zapscanner/views.py", line 120, in zap_scan
    if scans_status == '100':
NameError: global name 'scans_status' is not defined
[25/Oct/2018 09:37:50] "POST /zapscanner/zap_scan/ HTTP/1.1" 500 16025
All cookies
Target URL--- test.co.in
targets:----- jtest.co.in
invalid literal for int() with base 10: 'Does Not Exist'
Spider Completed
Scanning Target test.co.in
[u"'null' is not a valid UUID."]
invalid literal for int() with base 10: 'Does Not Exist'
Scan Completed

While launching a scan from Zap scanner, it shows Scan Completed with above error. 
I am using zap 2.7 and zap api is working fine.
Plz help.

**Comment by anandtiwarics** [comment]
Please make sure that you have created a project and assigned the project to the scanner while launching a scan.
However, I've pushed a code that fixed the error of "NameError: global name 'scans_status' is not defined"

Let me know if you still have an issue.

**Comment by v928** [comment]
thanks Anand for the reply..

Yes getting the same issue after creating the project and also, getting one more error

Scanning Target
/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField zap_scans_db.date_time received a naive datetime (2018-10-25 12:14:30.449964) while time zone support is active.
  RuntimeWarning)

**Comment by anandtiwarics** [comment]
This is normal error and its not related to scans. please re-start zap scanner API and check your zap settings in archery. Please follow document https://docs.archerysec.info/Scanners/zap-scanner/

Everything working fine from my end. Let me know if you still have an issue.
