### ISSUE TITLE
Add archerysec_push script for sample help

### ISSUE THREAD

**Issue by httpdss** [archerysec/archerysec#91]
**Is your feature request related to a problem? Please describe.**
the big question is "how do I easily push reports into archerysec?"

**Describe the solution you'd like**
I saw you have some archerysec_push script on your builds so it could be great to have something like that so that its used as a sample for projects wanting to implement the push logic on their builds

**Comment by anandtiwarics** [comment]
@httpdss are you talking about vulnerability scanners reports? if so then you can use archery REST API and write the script to push reports.  However, I'm writing archerysec CLI which help you to perform automation.

[Archery API Documentation](http://developers.archerysec.info)

**Comment by httpdss** [comment]
@anandtiwarics excellent! didnt know about that api documentation. 
yes, what i refer to in this issue could be perfectly done with the CLI you are mentioning. if you have that covered by some other open issue, just close this one :)

**Comment by anandtiwarics** [comment]
Initial CLI code pushed @ [https://github.com/archerysec/archerysec-cli](https://github.com/archerysec/archerysec-cli)

Still many work have to done. I'll let you know once its done.
