### ISSUE TITLE
Static 404 on docker

### ISSUE THREAD

**Issue by may215** [archerysec/archerysec#94]
I install from docker as you mentioned in the readme file.
All requirements are installed properly, and the interface loads in the browser without any items from /static

 "GET /dashboard/ HTTP/1.1" 200 18336
 "GET /static/css/bootstrap.min.css HTTP/1.1" 404 102
 "GET /static/css/bootstrap-responsive.min.css HTTP/1.1" 404 113
 "GET /static/css/uniform.css HTTP/1.1" 404 96
 "GET /static/css/select2.css HTTP/1.1" 404 96
 "GET /static/css/archery-style.css HTTP/1.1" 404 102
 "GET /static/css/archery-media.css HTTP/1.1" 404 102
 "GET /static/css/jquery.gritter.css HTTP/1.1" 404 103
 "GET /static/font-awesome/css/font-awesome.css HTTP/1.1" 404 114

I updated the docker file, re-install, but, still not fixed.

Thanks.

**Comment by anandtiwarics** [comment]
@may215 please check I have reverted the last pull request for debug toolbar. Hope this will solve the issue. Also please confirm.
